-- Reservation desk: allow trusted staff to enter a walk-in/phone request on behalf of guests.
create or replace function public.desk_request_poker_reservation(p_game uuid,p_name text,p_arrival timestamptz)
returns uuid language plpgsql security definer set search_path=public as $$
declare g public.reservation_games%rowtype; n text; rid uuid;
begin
 if public.current_app_role() not in ('admin','staff') then raise exception 'Staff login required'; end if;
 select * into g from public.reservation_games where id=p_game and is_open for update;
 if not found then raise exception 'Reservations are closed'; end if;
 n:=trim(coalesce(p_name,''));
 if length(n)<2 or length(n)>80 then raise exception 'Player name must be 2-80 characters'; end if;
 if p_arrival is null then raise exception 'Arrival time required'; end if;
 if exists(select 1 from public.reservations where game_id=p_game and lower(player_name)=lower(n) and status in ('pending','confirmed','waitlisted','checked_in')) then
 raise exception 'An active reservation already exists for this player'; end if;
 insert into public.reservations(game_id,player_name,arrival_at,note)
 values(p_game,n,p_arrival,'[DESK]') returning id into rid;
 insert into public.reservation_audit(reservation_id,new_status,actor) values(rid,'pending',auth.uid());
 return rid;
end $$;
revoke all on function public.desk_request_poker_reservation(uuid,text,timestamptz) from public;
grant execute on function public.desk_request_poker_reservation(uuid,text,timestamptz) to authenticated;

create table if not exists public.reservation_messages(
 id bigint generated by default as identity primary key,
 reservation_id uuid not null references public.reservations(id) on delete cascade,
 author_id uuid not null default auth.uid(),
 author_name text not null default '',
 body text not null check(length(body) between 1 and 500),
 translation text not null default '',
 created_at timestamptz not null default now()
);
create index if not exists reservation_messages_reservation_idx on public.reservation_messages(reservation_id,created_at);
alter table public.reservation_messages enable row level security;
drop policy if exists "reservation staff message read" on public.reservation_messages;
create policy "reservation staff message read" on public.reservation_messages
for select to authenticated using(public.current_app_role() in ('admin','staff'));
drop policy if exists "reservation staff message send" on public.reservation_messages;
create policy "reservation staff message send" on public.reservation_messages
for insert to authenticated with check(public.current_app_role() in ('admin','staff') and author_id=auth.uid());
-- Messages are immutable. Translations for preset phrases are persisted alongside originals.
