-- Keep only Google Sheet player master data in the web app.
-- Source: DREAM TIME ATTACK 자동 정산 / 플레이어 명단
-- Game history intentionally removed per operator request.

alter table public.players add column if not exists note text;

insert into public.agencies(code, rate, active)
values
  ('CANADA', 0, true),
  ('CHINA', 0, true),
  ('FRANCE', 0, true),
  ('GERMANY', 0, true),
  ('HOUSE', 0, true),
  ('INDIA', 0, true),
  ('JAPAN', 0, true),
  ('KOREA', 0, true),
  ('KOREA2', 0, true),
  ('MONGOL', 0, true),
  ('PHILIPPINES', 0, true),
  ('RUSSIA', 0, true),
  ('UK', 0, true),
  ('VIETNAM', 0, true)
on conflict (code) do nothing;

delete from public.game_entries;
delete from public.players;

with src(name,card_no,agency_code,note) as (
  values
    ('GAL YOO SEUNG', '', 'KOREA', ''),
    ('PARK JAE RIM', '', 'KOREA', ''),
    ('KIM MIN SEONG', '', 'KOREA', ''),
    ('LUCKY', '', 'KOREA', ''),
    ('LEE HONG RYE', '', 'KOREA', ''),
    ('KIM YOUNH JUN', '', 'KOREA', ''),
    ('PARK MIN JUNG', '', 'KOREA', ''),
    ('LI JIN MING', '', 'KOREA', ''),
    ('LEE SI WON', '292', 'KOREA', ''),
    ('BAEK JAE HO', '', 'KOREA', ''),
    ('KIM SIN AE', '', 'KOREA', ''),
    ('LEE SEUNG WON', '', 'KOREA', ''),
    ('HA SUNG MIN', '', 'KOREA', ''),
    ('CHOI JIN WOO', '', 'KOREA', ''),
    ('KIM CHANG JUN', '', 'KOREA', ''),
    ('YOO EUN JUNG', '', 'KOREA', ''),
    ('UM JI EUN', '', 'KOREA', ''),
    ('SHIN JAE WOOK', '', 'KOREA', ''),
    ('LIM YO HWAN', '', 'KOREA', ''),
    ('LEE SANG WOO', '', 'KOREA', ''),
    ('KANG DONG JIN', '', 'KOREA', ''),
    ('KIM JIN SUNG', '', 'KOREA', ''),
    ('GU JU WAN', '', 'KOREA', ''),
    ('JANG WON IL', '', 'KOREA', ''),
    ('KIM YE RIM', '', 'KOREA', ''),
    ('KANG JAE HYOUNG(B)', '1554', 'KOREA', '크레딧'),
    ('KIM DO YEON', '', 'KOREA', ''),
    ('KIM DO HYEONG', '', 'KOREA', ''),
    ('LEE TA NA', '', 'KOREA', ''),
    ('KIM SEUNG KYU', '1250', 'KOREA', '크레딧'),
    ('KIM MAN JUNG', '451', 'KOREA', ''),
    ('LEE HYUN JOO', '', 'KOREA', ''),
    ('JUNG WON SEOK', '', 'KOREA', ''),
    ('HWANG WHUI YEONG', '', 'KOREA', ''),
    ('LIM JUNE HO', '1215', 'KOREA', ''),
    ('KWON SANG SEOK', '', 'KOREA', ''),
    ('KANG DONG HUN', '1174', 'KOREA', ''),
    ('KWON OH YOUNG', '1614', 'KOREA', ''),
    ('LEE SUNG HOON', '', 'KOREA', ''),
    ('CHOI DUE HYUN', '', 'KOREA', ''),
    ('PARK KYOUNG WON', '', 'KOREA', ''),
    ('YEO SAN', '', 'KOREA', ''),
    ('CHOI KWANG GUK', '', 'KOREA', ''),
    ('KIM DAE HWAN', '', 'KOREA', ''),
    ('AHN JAE MIN', '', 'KOREA', ''),
    ('JANG EUN SANG', '', 'KOREA', ''),
    ('JEONG JONG SEONG', '', 'KOREA', ''),
    ('KIM MIN', '', 'KOREA', ''),
    ('SEO JEONG CHUN', '', 'KOREA', ''),
    ('JIN BYUNG WAN', '', 'KOREA', ''),
    ('LEE SANG MIN', '', 'KOREA', ''),
    ('KWON HYUCK PYO', '1610', 'KOREA', ''),
    ('SIN DO HOON', '', 'KOREA', ''),
    ('KIM YEON JOONG', '', 'KOREA', ''),
    ('PARK KEON WOO', '', 'KOREA', ''),
    ('JUNG SUNG WON', '', 'KOREA', ''),
    ('OH SUNG HUYN', '', 'KOREA', ''),
    ('KIM TEA SU', '1817', 'KOREA', ''),
    ('KIM JONG WOO', '', 'KOREA', ''),
    ('CHA YU JIN', '', 'KOREA', ''),
    ('RYU WON MO', '', 'KOREA', ''),
    ('JOO YOUNG SU', '', 'KOREA', ''),
    ('KIM YOO JIN', '', 'KOREA', ''),
    ('JUNG HUYN YEL', '', 'KOREA', ''),
    ('JUNG WOO YOUNG', '', 'KOREA', ''),
    ('KANG SUNG YUN', '', 'KOREA', ''),
    ('JANG EUN HO', '', 'KOREA', ''),
    ('OH SOO HYUNG', '', 'KOREA', ''),
    ('SONG MIN BONG', '1865', 'KOREA', ''),
    ('YANG KWANG SUP', '1864', 'KOREA', ''),
    ('KIM JONG SOO', '', 'KOREA', ''),
    ('KIM IK JUN', '', 'KOREA', ''),
    ('CHA YOUNG SIK', '', 'KOREA', ''),
    ('SIM JI HOON', '1830', 'KOREA', ''),
    ('LEE DONG HAN', '', 'KOREA', ''),
    ('LEE OH HUYN', '', 'KOREA', ''),
    ('LEE KI WOO', '', 'KOREA', ''),
    ('JEONG JI HUN', '', 'KOREA', ''),
    ('HUYN JUN SON', '', 'KOREA', ''),
    ('JONG HA GUEN', '', 'KOREA', ''),
    ('GIL JANG JUN', '', 'KOREA', ''),
    ('JEONG MIN SEONG', '', 'KOREA', ''),
    ('YOU YEON JONG', '', 'KOREA', ''),
    ('KIM KYOUNG TAE', '1892', 'KOREA', ''),
    ('JEONG HAE UN', '', 'KOREA', ''),
    ('KOO TAE WAN', '', 'KOREA', ''),
    ('YIM BYOUNG SOON', '', 'KOREA', ''),
    ('KWON SUN CHOL', '', 'KOREA', ''),
    ('CHOI BONG SIK', '', 'KOREA', ''),
    ('NAM KWANG WYK', '', 'KOREA', ''),
    ('KANG TAEK WON', '', 'KOREA', ''),
    ('SOK HUNG DOO', '', 'KOREA', ''),
    ('JANG JUN', '', 'KOREA', ''),
    ('JANG JI SEUNG', '', 'KOREA', ''),
    ('KIM JINH WAN', '', 'KOREA', ''),
    ('KIM MUN SUK', '', 'KOREA', ''),
    ('BAE JAE SUNG', '', 'KOREA', ''),
    ('SIN HYUN WOO', '', 'KOREA', ''),
    ('EUM JUNG YOUNG', '', 'KOREA', ''),
    ('KU KYUNG SEO', '', 'KOREA', ''),
    ('LIM DONG SOO', '', 'KOREA', ''),
    ('JANG WOONG', '', 'KOREA', ''),
    ('LEE AN HO', '', 'KOREA', ''),
    ('NAM KWANG SYK', '', 'KOREA', ''),
    ('KIM SE RIM', '', 'KOREA', ''),
    ('HAN SANG WOON', '', 'KOREA', ''),
    ('YANG HOON MIN', '', 'KOREA', ''),
    ('KIM SUNG IL', '', 'KOREA', ''),
    ('KIM JI HAN', '', 'KOREA', ''),
    ('CHOI YOUNG YONG', '', 'KOREA', ''),
    ('LEE DONG HWAN', '', 'KOREA', ''),
    ('PARK SUNG BOK', '', 'KOREA', ''),
    ('BAIK SU JIN', '', 'KOREA', ''),
    ('OH KUN', '', 'KOREA', ''),
    ('PARK JIN YEONG', '', 'KOREA', ''),
    ('CHO DAE HEE', '', 'KOREA', ''),
    ('KIM SIN WOO', '', 'KOREA', ''),
    ('KIM SANG HYUN', '', 'KOREA', ''),
    ('MAENG SANG KYO', '842', 'KOREA', ''),
    ('JEONG JONG YUN', '', 'KOREA', ''),
    ('CHOI YEON KUK', '', 'KOREA', ''),
    ('LEE KYUN GIL', '', 'KOREA', ''),
    ('KIM YOUNG BAE', '', 'KOREA', ''),
    ('PARK JONG BEOM', '', 'KOREA', ''),
    ('LEE DOO SUK', '', 'KOREA', ''),
    ('LEE CHAN YEONG', '', 'KOREA', ''),
    ('KIM DONG WOOK', '', 'KOREA', ''),
    ('KIM HOON MIN', '', 'KOREA', ''),
    ('KONG YEON HO', '', 'KOREA', ''),
    ('KIM WOO HYUN', '', 'KOREA', ''),
    ('KIM DONG WOOK', '', 'KOREA', ''),
    ('KIM SIN WOO', '', 'KOREA', ''),
    ('SONG MINKYN', '', 'KOREA', ''),
    ('KIM YUN HWAN', '2006', 'KOREA', ''),
    ('KIM PHIL', '', 'KOREA', ''),
    ('PARK SEUNG JUN', '', 'KOREA', ''),
    ('KIM JONG EUN', '', 'KOREA', ''),
    ('NO HYUNG WOO', '', 'KOREA', ''),
    ('KIM SANG WON', '', 'KOREA', ''),
    ('KIM GEON YEON', '', 'KOREA', ''),
    ('KIM SEANG YULM', '', 'KOREA', ''),
    ('YOO SUN HO', '', 'KOREA', ''),
    ('PARK SUNG JU', '', 'KOREA', ''),
    ('HEANG CHAN WOO', '', 'KOREA', ''),
    ('MI NA SON', '', 'KOREA', ''),
    ('WON JONG SUN', '', 'KOREA', ''),
    ('NA HYUN MI', '', 'KOREA', ''),
    ('YOO SUN HO', '', 'KOREA', ''),
    ('JEON JONG CHEOL', '', 'KOREA', ''),
    ('KIM SUNG EUN', '', 'KOREA', ''),
    ('BEAK YOUNG SEOK', '', 'KOREA', ''),
    ('LEE SANG GEOL', '1645', 'KOREA', ''),
    ('KIM GEON OH', '', 'KOREA', ''),
    ('JUNG CHUL HAK', '', 'KOREA', ''),
    ('BAK CHUN GI', '', 'KOREA', ''),
    ('KIM HYUNG CHUL', '', 'KOREA', ''),
    ('PARK YONG HOON', '', 'KOREA', ''),
    ('KIM DAE GON', '', 'KOREA', ''),
    ('YIM SANG WOOK', '', 'KOREA', ''),
    ('YU JEONG YEOL', '', 'KOREA', ''),
    ('LEE JAE HOON', '2064', 'KOREA', ''),
    ('CHO DONG HAE', '', 'KOREA', ''),
    ('SHIN GI CHAN', '', 'KOREA', ''),
    ('CHOI DSI PYUNG', '', 'KOREA', ''),
    ('KIM MIN KI', '', 'KOREA', ''),
    ('KIM HAN SANG', '974', 'KOREA', ''),
    ('JU MIN SUN', '', 'KOREA', ''),
    ('LEE BYOUNG MIN', '', 'KOREA', ''),
    ('KIM BYUNG HOON', '', 'KOREA', ''),
    ('BYEON JUN SIK', '', 'KOREA', ''),
    ('KIM SE JONG', '', 'KOREA', ''),
    ('KANG YONG WOO', '', 'KOREA', ''),
    ('YOO YEOM HYE', '', 'KOREA', ''),
    ('KIM SEONG HOON', '', 'KOREA', ''),
    ('SHIN HAN YONG', '', 'KOREA', ''),
    ('JEON HAE JUN', '', 'KOREA', ''),
    ('LEE KI JUNG', '', 'KOREA', ''),
    ('KIM KYUN GIL', '', 'KOREA', ''),
    ('JUNG SEON MIN', '', 'KOREA', ''),
    ('KONG BYEONG HUN', '', 'KOREA', ''),
    ('KKIM SEOK TAE', '', 'KOREA', ''),
    ('YOON SE HO', '', 'KOREA', ''),
    ('KIM JI WOO', '', 'KOREA', ''),
    ('JANG YE CHAN', '', 'KOREA', ''),
    ('LEE JAE HYUK', '', 'KOREA', ''),
    ('CHA KYUNG HWA', '', 'KOREA', ''),
    ('SONG SEUN GIK', '', 'KOREA', ''),
    ('OH WOO SEOK', '', 'KOREA', ''),
    ('KIM SEONG BEOM', '', 'KOREA', ''),
    ('KANG HYUN WOO', '2152', 'KOREA', ''),
    ('LEE MOON JONG', '', 'KOREA', ''),
    ('KIM TAE IL', '', 'KOREA', ''),
    ('EUN JEONG GYUN', '2153', 'KOREA', ''),
    ('LEE SEUNG JIN', '', 'KOREA', ''),
    ('KIM GAH YEON', '', 'KOREA', ''),
    ('BAG JUN CHUL', '', 'KOREA', ''),
    ('PARK YOUNG JUN', '', 'KOREA', ''),
    ('KIM DO HYEONG', '', 'KOREA', ''),
    ('LEE JOON HYEOK', '', 'KOREA', ''),
    ('OH HYO SUK', '', 'KOREA', ''),
    ('PARK JU HYUN', '2170', 'KOREA', ''),
    ('JEAN DAE EUN', '', 'KOREA', ''),
    ('KIM HENRY', '', 'KOREA', ''),
    ('KIM HAN SANG', '', 'KOREA', ''),
    ('LEE BYEON WOO', '2188', 'KOREA', ''),
    ('LEE JAE YONG', '', 'KOREA', ''),
    ('KIM SE YOUNG', '', 'KOREA', ''),
    ('KIM KYONG TAE', '2192', 'KOREA', ''),
    ('PARK CHEOL JONG', '', 'KOREA', ''),
    ('NA BUYNG OH', '', 'KOREA', ''),
    ('YU YEONG BEOM', '', 'KOREA', ''),
    ('CHOL YOUNG JUN', '', 'KOREA', ''),
    ('KWON DAE JUNG', '', 'KOREA', ''),
    ('LEE SANG HUN', '', 'KOREA', ''),
    ('KIM AH YEONG', '', 'KOREA', ''),
    ('KWON OH KEUN', '', 'KOREA', ''),
    ('HONG HUYN JU', '', 'KOREA', ''),
    ('HONG HYUN EUI', '', 'KOREA', ''),
    ('YANG TAE HYUK', '', 'KOREA', ''),
    ('SEO DONG MIN', '', 'KOREA', ''),
    ('PARK HYUNG JOON', '', 'KOREA', ''),
    ('LEE DO GYUN', '', 'KOREA', ''),
    ('PARK GEON', '', 'KOREA', ''),
    ('KWON HYUN WOO', '', 'KOREA', ''),
    ('LEE SANG DEUK', '', 'KOREA', ''),
    ('KIM HO SEOK', '', 'KOREA', ''),
    ('KIM SEOK JIN', '', 'KOREA', ''),
    ('LEE JU SEOK', '2223', 'KOREA', ''),
    ('SHIN WON HO', '2224', 'KOREA', ''),
    ('OH YONG JAE', '', 'KOREA', ''),
    ('KIM KI TAE', '', 'KOREA', ''),
    ('HWANG IN CHUL', '', 'KOREA', ''),
    ('LEE JUN HO', '', 'KOREA', ''),
    ('KIM NYEON WOO', '', 'KOREA', ''),
    ('LEE YONG HO', '', 'KOREA', ''),
    ('KIM DO HUN', '', 'KOREA', ''),
    ('YOUN SO YEONG', '', 'KOREA', ''),
    ('LEE YU JUN', '', 'KOREA', ''),
    ('YOO HO SUN', '', 'KOREA', ''),
    ('PARK SEONG JIN', '', 'KOREA', ''),
    ('LEE DO GEON', '', 'KOREA', ''),
    ('AHN HYUN JU', '', 'KOREA', ''),
    ('LEE SANG HEE', '', 'KOREA', ''),
    ('YANG HEE CHEOL', '', 'KOREA', ''),
    ('LEE JAE HO', '2254', 'KOREA', ''),
    ('YOON HYEO NIL', '', 'KOREA', ''),
    ('CHOI JONG KU', '', 'KOREA', ''),
    ('YOU WOOK JIN', '', 'KOREA', ''),
    ('SEO MIN BEOM', '', 'KOREA', ''),
    ('JUNG JONG BOK', '', 'KOREA', ''),
    ('LEE YUN WOO', '', 'KOREA', '마지막 결제'),
    ('CHAE JEONG HUN', '', 'KOREA', ''),
    ('LIM SE WOOK', '', 'KOREA', ''),
    ('KIM WAN', '', 'KOREA', ''),
    ('LEE JEONG RO', '', 'KOREA', ''),
    ('SIM JEA HOON', '2266', 'KOREA', ''),
    ('SEOK DONG GYEOP', '2277', 'KOREA', ''),
    ('HYUN DONG HUN', '', 'KOREA', ''),
    ('LIM JIN MIN', '', 'KOREA', ''),
    ('KIM DO HYEONG B', '', 'KOREA', ''),
    ('KIM YE RIN', '', 'KOREA', ''),
    ('KIM YUN KI', '', 'KOREA', ''),
    ('YANG JUN HYEOK', '2293', 'KOREA', ''),
    ('LIM JI HUN', '', 'KOREA', ''),
    ('LEE JIN HYOUNG', '', 'KOREA', ''),
    ('IM DEA YOUNG', '', 'KOREA', ''),
    ('BEAK SEUNG HWAN', '', 'KOREA', ''),
    ('LEE JEONG UNG', '', 'KOREA', ''),
    ('PARK SEO HEE', '', 'KOREA', ''),
    ('CHOI YUN SU', '', 'KOREA', ''),
    ('JANG KWANG SOO', '', 'KOREA', ''),
    ('CHOI YEON KUK', '', 'KOREA', ''),
    ('JEONG JONG YUN', '', 'KOREA', ''),
    ('LEE HYUN SOO', '', 'KOREA', ''),
    ('EUN SE JIN', '', 'KOREA', ''),
    ('LEE KI WON', '', 'KOREA', ''),
    ('JEON JANG WON', '', 'KOREA', ''),
    ('BYUN JAE MIN', '', 'KOREA', ''),
    ('HAN YU SEUNG', '', 'KOREA', ''),
    ('MOON BYOUNG SAM', '', 'KOREA', ''),
    ('YOON IN JUN', '', 'KOREA', ''),
    ('KANG YU IN', '', 'KOREA', ''),
    ('MHIN GYOUNG CHO', '', 'KOREA', ''),
    ('KIM KYU HYUN', '2341', 'KOREA', ''),
    ('HA HO SEONG', '', 'KOREA', ''),
    ('LEE JEONG BOK', '', 'KOREA', ''),
    ('HSU SEUNG HYUN', '', 'KOREA', ''),
    ('LEE BYUNG WOOK', '', 'KOREA', ''),
    ('YUN WON JIN', '', 'KOREA', ''),
    ('LEE YEON JUN', '', 'KOREA', ''),
    ('JEONG JI MAN', '', 'KOREA', ''),
    ('JUN HONG IK', '', 'KOREA', ''),
    ('KIM DEOK SOO', '', 'KOREA', ''),
    ('LEE HO YOUNG', '', 'KOREA', ''),
    ('BAE HO CHEOL', '', 'KOREA', ''),
    ('KIM MIN GYU', '', 'KOREA', ''),
    ('SHIN HYEON SU', '', 'KOREA', ''),
    ('LEE SANG WOO', '', 'KOREA', ''),
    ('HONG KI DEOK', '', 'KOREA', ''),
    ('OH YOUNG HWAN', '', 'KOREA', ''),
    ('LEE YE RIN', '', 'KOREA', ''),
    ('DO MIN YONG', '', 'KOREA', ''),
    ('LEE TAE CHUL', '', 'KOREA', ''),
    ('KANG SUN GU', '', 'KOREA', ''),
    ('PARK KI SEON', '', 'KOREA', ''),
    ('KIM JUN HAN', '2376', 'KOREA', ''),
    ('PARK KYUNG HOON', '2377', 'KOREA', ''),
    ('LEE KYOUNG CHUL', '2378', 'KOREA', ''),
    ('PARK HYUN WOO', '2379', 'KOREA', ''),
    ('KIM DO KYEONG', '2385', 'KOREA', ''),
    ('JUNG JAE IK', '2386', 'KOREA', ''),
    ('CHO MAN JIN', '2390', 'KOREA', ''),
    ('YEON HWAL', '2391', 'KOREA', ''),
    ('SUN WOO KIM', '2402', 'KOREA', ''),
    ('LEE SANG JIK', '2404', 'KOREA', ''),
    ('KANG MIN WOOK', '2403', 'KOREA', ''),
    ('JANG KWANG HYUN', '2401', 'KOREA', ''),
    ('LEE SEUNG CHAN', '2269', 'KOREA', ''),
    ('KIM YOUNG MIN', '2405', 'KOREA', ''),
    ('WOO OBAMA AHMED', '2409', 'KOREA', ''),
    ('KWON GOO HE', '2410', 'KOREA', ''),
    ('JEONG JIN WON', '2415', 'KOREA', ''),
    ('KIM NA YOUN', '2416', 'KOREA', ''),
    ('LIM JAE DUK', '2419', 'KOREA', ''),
    ('YOO JAE SUNG', '2418', 'KOREA', ''),
    ('PARK CHAN SOO', '2420', 'KOREA', ''),
    ('KIM SAE JUN', '2422', 'KOREA', ''),
    ('PARK SE WON', '2423', 'KOREA', ''),
    ('KIM JIN GOO', '2424', 'KOREA', ''),
    ('KIM DEUK SIN', '2425', 'KOREA', ''),
    ('PARK JONG IL', '2426', 'KOREA', ''),
    ('RYU TAE WON', '2427', 'KOREA', ''),
    ('LEE JAE REONG', '2432', 'KOREA', ''),
    ('KIM NO YOUNG', '2433', 'KOREA', ''),
    ('JUNG WON YOUNG', '2431', 'KOREA', ''),
    ('LEE JAE JUNG', '', 'KOREA', ''),
    ('LEE SEUNG HOON', '', 'KOREA', ''),
    ('PARK BO MIN', '', 'KOREA', ''),
    ('HWANG HW IJIN', '', 'KOREA', ''),
    ('KIM SEON HAK', '2445', 'KOREA', ''),
    ('LEE SUNG WON', '', 'KOREA', ''),
    ('HONG JIN SU', '2443', 'KOREA', ''),
    ('PARK JEONG HYEON', '2446', 'KOREA', ''),
    ('LEE SO YOUN', '2450', 'KOREA', ''),
    ('PARK SOO MIN', '2452', 'KOREA', ''),
    ('KIM SI HYUN', '2451', 'KOREA', ''),
    ('KOO BON HYUNG', '2454', 'KOREA', ''),
    ('BYUN KEUN HYUCK', '2455', 'KOREA', ''),
    ('SHIN IN GYU', '2456', 'KOREA', ''),
    ('MUN DA YAE', '2458', 'KOREA', ''),
    ('JANG HYEON SEONG', '2457', 'KOREA', ''),
    ('MOON JOON YOUNG', '2460', 'KOREA', ''),
    ('YEO IN JIN', '2462', 'KOREA', ''),
    ('BAE DAE HO', '2482', 'KOREA', ''),
    ('KIM HYE WON', '2480', 'KOREA', ''),
    ('KWAK BYUNG KOOK', '2485', 'KOREA', ''),
    ('LEE SEONG GI', '2488', 'KOREA', ''),
    ('LEE GEON HO', '2487', 'KOREA', ''),
    ('KIM MOON SIK', '2493', 'KOREA', ''),
    ('JEON HA SEOK', '2503', 'KOREA', ''),
    ('SEONG CHI GUK', '2500', 'KOREA', ''),
    ('SON RAK WON', '2501', 'KOREA', ''),
    ('SEO MIN GI', '2506', 'KOREA', ''),
    ('KIM YONG BEOM', '2499', 'KOREA', ''),
    ('PARK JUNG NAM', '2508', 'KOREA', ''),
    ('KIM DONG HUI', '2516', 'KOREA', ''),
    ('YANG IN SUK', '2522', 'KOREA', ''),
    ('JEONG SHU HYEON', '2526', 'KOREA', ''),
    ('LEE JONG SU', '2528', 'KOREA', ''),
    ('OH DONG WON', '2527', 'KOREA', ''),
    ('SONG DONG HUN', '2492', 'KOREA', ''),
    ('WOO JUNG DAE', '2529', 'KOREA', ''),
    ('HWANG DONG YU', '2534', 'KOREA', ''),
    ('KWAK GUN', '2542', 'KOREA', ''),
    ('LEE JAE HYEON', '2547', 'KOREA', ''),
    ('LEE SANG CHUL', '2548', 'KOREA', ''),
    ('HWANG SEONG IL', '1682', 'KOREA', ''),
    ('JUNG HO CHAN', '2551', 'KOREA', ''),
    ('HWANG BO HAN', '2558', 'KOREA', ''),
    ('SUL DAE SUNG', '2553', 'KOREA', ''),
    ('KIM KYU HYUN B', '2563', 'KOREA', ''),
    ('HA DAE RYUNG', '2565', 'KOREA', ''),
    ('JIN YONG BAE', '1683', 'KOREA', ''),
    ('JUNG JI HYUK', '2576', 'KOREA', ''),
    ('LEE SEOK MIN B', '2586', 'KOREA', ''),
    ('GWAK JOO HO', '2583', 'KOREA', ''),
    ('MOON BAE JUN', '2590', 'KOREA', ''),
    ('SONG HWAN HUI', '2591', 'KOREA', ''),
    ('KIM DOO HO', '2593', 'KOREA', ''),
    ('LEE TAE JEUNG', '2594', 'KOREA', ''),
    ('KIM SUNG SU', '2601', 'KOREA', ''),
    ('KIM JAE HYUN', '2600', 'KOREA', ''),
    ('KWEON SUNG JOO', '2602', 'KOREA', ''),
    ('LEE YONG HA', '2608', 'KOREA', ''),
    ('LEE WON JIN', '2609', 'KOREA', ''),
    ('SHIN HAN JAE', '2611', 'KOREA', ''),
    ('CHO JA YONG', '2616', 'KOREA', ''),
    ('BACK JONG BAE', '2614', 'KOREA', ''),
    ('CHOI SANG KYOUNG', '2624', 'KOREA', ''),
    ('KIM JUNG HOON', '2629', 'KOREA', ''),
    ('JEON SANG HUN', '2631', 'KOREA', ''),
    ('KANG MIN SU', '2630', 'KOREA', ''),
    ('YOO HONG YOL', '1358', 'KOREA', ''),
    ('KIM U YEON', '2639', 'KOREA', ''),
    ('NA YANG HO', '2644', 'KOREA', ''),
    ('CHO JUNG HYEON', '2640', 'KOREA', ''),
    ('KIM DA MIN', '2647', 'KOREA', ''),
    ('KIM JAE BEOM', '2649', 'KOREA', ''),
    ('KIM HAK SEONG', '2651', 'KOREA', ''),
    ('KIM JUN', '2652', 'KOREA', ''),
    ('KIM YOUNG SU', '2657', 'KOREA', ''),
    ('LEE YOUNG HUN', '2660', 'KOREA', ''),
    ('PARK GYU DONG', '2662', 'KOREA', ''),
    ('CHO KWAN HYEON', '2666', 'KOREA', ''),
    ('JUN HWAN EUI', '2665', 'KOREA', ''),
    ('SHIN SANG HYEOK', '2664', 'KOREA', ''),
    ('KIM RI HWA', '2659', 'KOREA', ''),
    ('KIM TAE HWAN', '2658', 'KOREA', ''),
    ('SEONG HO CHO', '2675', 'KOREA', ''),
    ('JUN MYUNG HYUN', '2680', 'KOREA', ''),
    ('KIM YEON DEUG', '2682', 'KOREA', ''),
    ('KIM DONG GYU', '2685', 'KOREA', ''),
    ('KIM MUN SUB', '2694', 'KOREA', ''),
    ('PARK JIN SU', '2700', 'KOREA', ''),
    ('KIM YEONG MIN', '2708', 'KOREA', ''),
    ('SONG SUL', '2725', 'KOREA', ''),
    ('LEE CHUNG HI', '2724', 'KOREA', ''),
    ('KU BON CHAN', '2726', 'KOREA', ''),
    ('GANG SEONG HOON', '2730', 'KOREA', ''),
    ('KIM JI WON', '2731', 'KOREA', ''),
    ('PARK JONG HYEON', '2743', 'KOREA', ''),
    ('LIM CHAN BIN', '2746', 'KOREA', ''),
    ('HEO GYEONG HO', '2748', 'KOREA', ''),
    ('CHOI WON YOUNG', '2747', 'KOREA', ''),
    ('KIM HUI SUNG', '2749', 'KOREA', ''),
    ('JI SUNG RYEOL', '3068', 'KOREA', ''),
    ('LEE DONG HYUN', '3054', 'KOREA', ''),
    ('LIM SEOM WOO', '3055', 'KOREA', ''),
    ('HAN GI YOON', '3056', 'KOREA', ''),
    ('LEE HEE HAWN', '3057', 'KOREA', ''),
    ('CHO YONG GI', '3059', 'KOREA', ''),
    ('KIM JAE HO', '3060', 'KOREA', ''),
    ('KIM BEOM WOO', '3066', 'KOREA', ''),
    ('OH SO DAM', '3065', 'KOREA', ''),
    ('KIM YANG GOO', '3064', 'KOREA', ''),
    ('BAE JEONG HWAN', '3061', 'KOREA', ''),
    ('KOO BON JAE', '3073', 'KOREA', ''),
    ('JUNG KYU WOON', '3076', 'KOREA', ''),
    ('IM MIN HYEOK', '3081', 'KOREA', ''),
    ('LEE DO HYEON', '3080', 'KOREA', ''),
    ('KIM CHANG HUN', '3082', 'KOREA', ''),
    ('LEE MYEONG HYEON', '3083', 'KOREA', ''),
    ('SHIN YOENG SANG', '3090', 'KOREA', ''),
    ('NAM HYUN CHOEL', '3092', 'KOREA', ''),
    ('OH JOO SEOB', '3093', 'KOREA', ''),
    ('CHOI MIN HO', '3033', 'KOREA', ''),
    ('CHOI HUN TAE', '3011', 'KOREA', ''),
    ('CHO SEONG HO B', '3012', 'KOREA', ''),
    ('HWANG JEONG HYEON', '2830', 'KOREA', ''),
    ('KIM SEONG RYEONG', '3096', 'KOREA', ''),
    ('KIM GYU RI', '2814', 'KOREA', ''),
    ('SEO JUN GI', '2813', 'KOREA', ''),
    ('KIM JONG DUCK', '3097', 'KOREA', ''),
    ('PARK TAE HOON', '3098', 'KOREA', ''),
    ('JUNG HYO GEN', '3100', 'KOREA', ''),
    ('KIM TAE JONG', '3102', 'KOREA', ''),
    ('KIM SE HYEON', '3106', 'KOREA', ''),
    ('YOON HOON', '3107', 'KOREA', ''),
    ('KIM JI WOONG', '3108', 'KOREA', ''),
    ('KIM JIN SU', '3110', 'KOREA', ''),
    ('KANG DONG HA', '3111', 'KOREA', ''),
    ('YOO SEUNG GYU', '2481', 'KOREA', ''),
    ('KANG MIN HEE', '3113', 'KOREA', ''),
    ('LEE BYEONG OCK', '3114', 'KOREA', ''),
    ('KIM HEE JIN', '3115', 'KOREA', '크레딧'),
    ('MIN BYOUNG MOON', '3116', 'KOREA', ''),
    ('LEE KYU HYEONG', '3120', 'KOREA', ''),
    ('LEE CHAN HO', '3122', 'KOREA', ''),
    ('SHIN DONG WOOK', '3123', 'KOREA', ''),
    ('IM TAE JONG', '3124', 'KOREA', ''),
    ('CHO YONG IL', '3131', 'KOREA', ''),
    ('SONG WOO SUK', '3133', 'KOREA', ''),
    ('GIL LEE CHAN SEAM', '3134', 'KOREA', ''),
    ('PARK WAN SEUNG', '2763', 'KOREA', ''),
    ('KIM HYOUNG YEOP', '2951', 'KOREA', ''),
    ('KIM DONG UK', '3154', 'KOREA', ''),
    ('LEE SEUNG JAE', '3153', 'KOREA', ''),
    ('YANG JUN SEO', '3152', 'KOREA', ''),
    ('PARK SEUNG HOON', '3158', 'KOREA', ''),
    ('IM JUN HYUNG', '3159', 'KOREA', ''),
    ('LEE JI HOON B', '3160', 'KOREA', ''),
    ('KIM JUNG YONG', '3163', 'KOREA', ''),
    ('YU JAE HYEONG', '3164', 'KOREA', ''),
    ('PARK JONG YOUN', '3168', 'KOREA', ''),
    ('JUN CHANG HWAN', '3169', 'KOREA', ''),
    ('KIM MYEONG SIK', '3170', 'KOREA', ''),
    ('YOON SHIN SUP', '3177', 'KOREA', ''),
    ('CHO MYUNG HOON', '3176', 'KOREA', ''),
    ('LEE CHAN YONG', '3179', 'KOREA', ''),
    ('KIM HA RIM', '3178', 'KOREA', ''),
    ('KIM MIN GUN', '3182', 'KOREA', ''),
    ('WON YEON UK', '3181', 'KOREA', ''),
    ('HWANG WOO JIN', '3184', 'KOREA', ''),
    ('YOUN JI HAN', '3183', 'KOREA', ''),
    ('HWANG JEONG MIN', '3019', 'KOREA', ''),
    ('HWANG SEUNG WOO', '3192', 'KOREA', ''),
    ('KIM BONG SIK', '3197', 'KOREA', ''),
    ('KIM DONG GYU B', '3198', 'KOREA', ''),
    ('SIM SUNG JUN', '3193', 'KOREA', ''),
    ('HONG YU JUN', '3199', 'KOREA', ''),
    ('LIM CHAE WOONG', '3201', 'KOREA', ''),
    ('KIM KI HYUN', '3214', 'KOREA', ''),
    ('HWANG YOUNG HWAN', '3215', 'KOREA', ''),
    ('NA TAE SUNG', '3236', 'KOREA', ''),
    ('KIM SU SUNG', '3229', 'KOREA', ''),
    ('PARK KUG SEUNG', '3228', 'KOREA', ''),
    ('LIM WON YOUNG', '3227', 'KOREA', ''),
    ('KANG WON CHAN', '3226', 'KOREA', ''),
    ('LEE SEOK HO', '3225', 'KOREA', ''),
    ('SHIN SEONG JUN', '3210', 'KOREA', ''),
    ('LIM SEONG HUN', '3231', 'KOREA', ''),
    ('CHO JU HYUN', '3232', 'KOREA', ''),
    ('KIM MU SAENG', '3240', 'KOREA', ''),
    ('YEO SEUNG WON', '3247', 'KOREA', ''),
    ('LEE TAE HO', '3246', 'KOREA', ''),
    ('LEE JONG MIN', '2194', 'KOREA', ''),
    ('MIN SOOK LEE', '3249', 'KOREA', ''),
    ('YOO CHANG KYUN', '3250', 'KOREA', ''),
    ('KIM CHAN HO', '2411', 'KOREA', ''),
    ('JUNG KYU HYUCK', '', 'KOREA', ''),
    ('JUNG SEUNG JIN', '780', 'KOREA', ''),
    ('AHN YOUNG JE', '3255', 'KOREA', ''),
    ('KIM JAE AN', '3259', 'KOREA', ''),
    ('YUN DAE YONG', '3258', 'KOREA', ''),
    ('KIM YOUNG SU', '3261', 'KOREA', ''),
    ('YANG CUIL AM', '3260', 'KOREA', ''),
    ('KUM JONG WOONG', '3254', 'KOREA', ''),
    ('KIM YOON SIK', '3264', 'KOREA', ''),
    ('LIM DUCK YOUNG', '3268', 'KOREA', ''),
    ('HWANG JAE SEONG', '3286', 'KOREA', ''),
    ('KIM SEUNG YOUNG', '3282', 'KOREA', ''),
    ('PARK SANG EUN', '3292', 'KOREA', ''),
    ('KIM JIN HYUG', '3293', 'KOREA', ''),
    ('JANG SEO U', '3296', 'KOREA', ''),
    ('YANG GWANG YONG', '3295', 'KOREA', ''),
    ('JEON HAN EUL', '3300', 'KOREA', ''),
    ('SHIN JOON KI', '3301', 'KOREA', ''),
    ('KIM KYEONG BAE', '3302', 'KOREA', ''),
    ('KIM SEOK MIN', '3304', 'KOREA', ''),
    ('PARK SUNG WOON', '3285', 'KOREA', ''),
    ('KIM HYEON U', '3267', 'KOREA', ''),
    ('JOUNG HA GUEN', '433', 'KOREA', ''),
    ('LA HEE JIN', '3312', 'KOREA', ''),
    ('KWON MI RA', '3281', 'KOREA', ''),
    ('JI HYUN WOO', '3315', 'KOREA', ''),
    ('LEE MIN YOUNG', '3317', 'KOREA', ''),
    ('CHOE SEONG BAE', '3318', 'KOREA', ''),
    ('KIM HA RAM', '2618', 'KOREA', ''),
    ('PARK JI SUNG', '3320', 'KOREA', ''),
    ('KIM SEOK MIN B', '3323', 'KOREA', ''),
    ('KA MAN HUYN', '3326', 'KOREA', ''),
    ('BEAK JONG SHIK', '575', 'KOREA', ''),
    ('SEO MIN SEOK', '3319', 'KOREA', ''),
    ('LIM TAE HYUNG', '3337', 'KOREA', ''),
    ('PARK TAE WOONG', '3338', 'KOREA', ''),
    ('CHOI BYEONG RYONG', '3340', 'KOREA', ''),
    ('PARK JAE HYUN', '3341', 'KOREA', ''),
    ('SEO SEONG KYUNG', '1874', 'KOREA', ''),
    ('CHUN WOO HYUN', '3344', 'KOREA', ''),
    ('CHUN JONG MIN', '3343', 'KOREA', ''),
    ('LEE WON IL', '3346', 'KOREA', ''),
    ('LEE DONG JIN', '3348', 'KOREA', ''),
    ('YOON WON SUNG', '3349', 'KOREA', ''),
    ('SHIN CHEOL WOONG', '3351', 'KOREA', ''),
    ('LEE WON HONG', '3350', 'KOREA', ''),
    ('LEE JONG JUN', '3356', 'KOREA', ''),
    ('CHO HYUNG YUL', '3357', 'KOREA', ''),
    ('HAM DONG MYUONG', '286', 'KOREA', ''),
    ('BAEK HYEON', '526', 'KOREA', ''),
    ('KANG IL MOOK', '3360', 'KOREA', ''),
    ('LEE SU HO', '3361', 'KOREA', ''),
    ('KO GUN WOO', '1501', 'KOREA', ''),
    ('HONG HYUN JU', '3347', 'KOREA', ''),
    ('SHIN JI HO', '3371', 'KOREA', ''),
    ('PARK HA YAN', '3372', 'KOREA', ''),
    ('BONG JAE YEON', '587', 'KOREA', ''),
    ('KIM KYUNG KU', '2125', 'KOREA', ''),
    ('HWANG JI WON', '3380', 'KOREA', ''),
    ('CHO JEONG WOO', '3379', 'KOREA', ''),
    ('YOOK GEUN YONG', '3382', 'KOREA', ''),
    ('KIM KYOUNG SU', '2020', 'KOREA', ''),
    ('LEE GYU BIN', '3394', 'KOREA', ''),
    ('GU TAE HEUNG', '3396', 'KOREA', ''),
    ('CHO YUN HO', '3398', 'KOREA', ''),
    ('LIM JUN YOUNG', '3402', 'KOREA', ''),
    ('CHO YOUNG SEUNG', '3403', 'KOREA', ''),
    ('SHIN SUNG MAN', '726', 'KOREA', ''),
    ('SEO SUNG HAE', '3418', 'KOREA', ''),
    ('KIM JUN HYUK', '3413', 'KOREA', ''),
    ('KIM JAE YU', '3425', 'KOREA', ''),
    ('GIM JAE YOUNG', '3417', 'KOREA', '크레딧'),
    ('KIM YOUNG IL', '3430', 'KOREA', ''),
    ('LEE HO JIN', '3431', 'KOREA', ''),
    ('SIM KYU CHUL', '3432', 'KOREA', ''),
    ('JEON YONG SEOK', '3433', 'KOREA', ''),
    ('HAN DAE YUB', '3434', 'KOREA', ''),
    ('SIM JAE LIM', '3435', 'KOREA', ''),
    ('NOH WOON KI', '1191', 'KOREA', ''),
    ('CHA JUNG HEE', '3436', 'KOREA', ''),
    ('YANG KYEONG SEOK', '3437', 'KOREA', ''),
    ('KIM JONG JIN', '3426', 'KOREA', ''),
    ('MUN JEONG HUN', '3443', 'KOREA', ''),
    ('KIM SOO UN', '3442', 'KOREA', ''),
    ('PARK HYO SEO', '3445', 'KOREA', ''),
    ('JIN MIN HYUK', '3448', 'KOREA', ''),
    ('LIM DONG WON', '3449', 'KOREA', ''),
    ('YOON HYO JEON', '3459', 'KOREA', ''),
    ('KIM HYUNG WOOK', '3458', 'KOREA', ''),
    ('SEO YONGJUN', '3457', 'KOREA', ''),
    ('SHIN HO YONG', '3461', 'KOREA', ''),
    ('LEE SEUNG HWAN', '3462', 'KOREA', ''),
    ('KWON TAE WON', '3463', 'KOREA', ''),
    ('KIM JI SEUNG', '3464', 'KOREA', ''),
    ('KIM MIN JUNG', '3460', 'KOREA', ''),
    ('LEE DONG GEUN', '3465', 'KOREA', ''),
    ('KIM SEUNG HYUN', '3473', 'KOREA', ''),
    ('HONG KEUN HO', '3474', 'KOREA', ''),
    ('PARK DA HEE', '3476', 'KOREA', ''),
    ('KIM SUNG MIN', '3477', 'KOREA', ''),
    ('AN HYEON WOO', '3478', 'KOREA', ''),
    ('KIM SEON GI', '3287', 'KOREA', ''),
    ('MOON MIN SOO', '3490', 'KOREA', ''),
    ('YANG JUN YOUNG', '3491', 'KOREA', ''),
    ('PARK JIN SOO', '3487', 'KOREA', ''),
    ('KANG JA MIN', '3485', 'KOREA', ''),
    ('OH YONG YEA', '2232', 'KOREA', ''),
    ('YOON SEUNG CHAN', '3492', 'KOREA', ''),
    ('SO JAE HYUN', '3493', 'KOREA', ''),
    ('LEE JUN HO', '2231', 'KOREA', ''),
    ('PARK GI BEOM', '3499', 'KOREA', ''),
    ('KIM CHUL MIN', '3501', 'KOREA', ''),
    ('JUNG HYO SEOP', '3500', 'KOREA', ''),
    ('YANG YOUNG HA', '3503', 'KOREA', ''),
    ('KIM JAE HYUN', '3502', 'KOREA', ''),
    ('KIM SON', '3504', 'KOREA', ''),
    ('KIM CHANG JUN', '3506', 'KOREA', ''),
    ('HA SEONG MIN', '3505', 'KOREA', ''),
    ('WOO YOONG WON', '3507', 'KOREA', ''),
    ('LEE SUNG HOON B', '3510', 'KOREA', ''),
    ('KIM NA EUN', '3512', 'KOREA', ''),
    ('PARK JIN YONG', '3514', 'KOREA', ''),
    ('SHIM JUN YONG', '3515', 'KOREA', ''),
    ('LEE SI YOUNG', '3516', 'KOREA', ''),
    ('LEE JONG HO', '3517', 'KOREA', ''),
    ('SONG EUN OK', '3520', 'KOREA', ''),
    ('JUNG HYUN JO', '3519', 'KOREA', ''),
    ('KIM TAE SEUNG', '529', 'KOREA', ''),
    ('KAL DEOK KI', '3527', 'KOREA', ''),
    ('KIM DAE HYUN', '3528', 'KOREA', ''),
    ('PYO JIE UN', '3529', 'KOREA', ''),
    ('OH KWANG SIK', '3525', 'KOREA', ''),
    ('KANG SHIN WOOK', '3524', 'KOREA', ''),
    ('KIM JAE HYUN B', '3534', 'KOREA', ''),
    ('CHOI MIN SEONG', '3535', 'KOREA', ''),
    ('KIM RYUNG WOO', '3536', 'KOREA', ''),
    ('LEE JEONG MOK', '3540', 'KOREA', ''),
    ('YOON YONG BAE', '3549', 'KOREA', ''),
    ('KIM BO EUM', '3550', 'KOREA', ''),
    ('KIM ERIC DAIL', '3552', 'KOREA', ''),
    ('OH HYUN JUN', '3548', 'KOREA', ''),
    ('CHOI JEONG SU', '3544', 'KOREA', ''),
    ('JEONG WOOJIN', '3553', 'KOREA', ''),
    ('SONG YOUNG TAK', '3543', 'KOREA', ''),
    ('KIM SEONG MIN', '3547', 'KOREA', ''),
    ('SHIN JAE KWAN', '3546', 'KOREA', ''),
    ('LEE KUN HEE', '3559', 'KOREA', ''),
    ('KO KANG YOON', '3561', 'KOREA', ''),
    ('LIM SUNG JIN', '3562', 'KOREA', ''),
    ('JEON SEONG KEE', '1364', 'KOREA', ''),
    ('HAN SUNG JUN', '3563', 'KOREA', ''),
    ('LEE GYEONG MIN', '3573', 'KOREA', ''),
    ('LEE HYEON JOON', '3571', 'KOREA', ''),
    ('MOON JUN SEO', '3572', 'KOREA', ''),
    ('LEE YONG JIN', '3574', 'KOREA', ''),
    ('LEE SOL', '3567', 'KOREA', ''),
    ('NAM TAE JIN', '3566', 'KOREA', ''),
    ('JUNG HAE SUNG', '3569', 'KOREA', ''),
    ('LEE GUN JUNE', '3576', 'KOREA', ''),
    ('SEO DEOK MYUNG', '3591', 'KOREA', ''),
    ('RYU MYUN GIL', '1681', 'KOREA', ''),
    ('OH JEONG HYEON', '3594', 'KOREA', ''),
    ('BAE SUNG HYUN', '3595', 'KOREA', ''),
    ('HONG JIN SU B', '3592', 'KOREA', ''),
    ('SONG SUNG CHUL', '3596', 'KOREA', ''),
    ('LEE SAE JIN', '3602', 'KOREA', ''),
    ('CHOI JONG WON', '3603', 'KOREA', ''),
    ('KWAK HYOUNG KEUN', '3605', 'KOREA', ''),
    ('SUN WOO MIN', '3604', 'KOREA', ''),
    ('PARK GUN', '3606', 'KOREA', ''),
    ('JEONG JUN YEONG', '3616', 'KOREA', ''),
    ('LEE DONG JAE', '3615', 'KOREA', ''),
    ('JUNG JU SEOK', '3622', 'KOREA', ''),
    ('PARK JEONG HYEOK', '3623', 'KOREA', ''),
    ('GO MIN YOUNG', '3619', 'KOREA', ''),
    ('SEONG JUN OH', '563', 'KOREA', ''),
    ('LIM DONG HYEON', '3626', 'KOREA', ''),
    ('LEE SANG YONG', '3630', 'KOREA', ''),
    ('KWAK JIN WOO', '1460', 'KOREA', ''),
    ('PARK JIN HYEONG', '3636', 'KOREA', ''),
    ('HAN KYU WOONG', '401', 'KOREA', ''),
    ('LEE HYUN SU B', '3639', 'KOREA', ''),
    ('LEE EUN SU', '3640', 'KOREA', ''),
    ('HONG SEUNG JO', '3641', 'KOREA', ''),
    ('KIM YOUNG JIN', '874', 'KOREA', ''),
    ('LEE JUN HUI B', '3649', 'KOREA', ''),
    ('KIM KYUNG MIN B', '3648', 'KOREA', ''),
    ('LEE YUN HWI', '3656', 'KOREA', ''),
    ('LEE SANG HWA', '3652', 'KOREA', ''),
    ('KANG JUNG KI', '3651', 'KOREA', ''),
    ('CHOI YUN HEE', '3666', 'KOREA', ''),
    ('LEE HAE SEUNG', '3667', 'KOREA', ''),
    ('HWANG BYUNG SEOK', '3672', 'KOREA', ''),
    ('NA HA NA', '3676', 'KOREA', '마지막 원화결제'),
    ('KANG SUM', '3675', 'KOREA', '마지막 원화결제'),
    ('KWAK DONG HYUK B', '3679', 'KOREA', ''),
    ('SUNG YOUNG HWAN', '3681', 'KOREA', ''),
    ('PARK JUNG HEE', '3686', 'KOREA', ''),
    ('JEONG HYUN JOO', '3685', 'KOREA', ''),
    ('JO WON SIK', '3684', 'KOREA', ''),
    ('KIM DO IK', '3683', 'KOREA', ''),
    ('YANG JI HUN', '3687', 'KOREA', ''),
    ('LEE MIN SU', '3688', 'KOREA', ''),
    ('KIM JOO YONG', '3691', 'KOREA', ''),
    ('LEE MIN GU', '3695', 'KOREA', ''),
    ('KIM SOON CHUL', '3696', 'KOREA', ''),
    ('LEE YEON GUN', '3700', 'KOREA', ''),
    ('KIM DONG HYUN', '3701', 'HOUSE', ''),
    ('LEE SEO YOUNG B', '3705', 'KOREA', ''),
    ('BEAK SANG MIN', '3704', 'KOREA', ''),
    ('CHOI SUNG HYUN', '3707', 'KOREA', ''),
    ('LEE SANG HYUN', '3708', 'KOREA', ''),
    ('YU HYUN SOO', '3711', 'KOREA', ''),
    ('LEE HUN PYO', '3713', 'KOREA', ''),
    ('HWANG SUNG PIL', '3717', 'KOREA', ''),
    ('HWANG HYUN WOO', '3719', 'KOREA', ''),
    ('PARK JUNG SEON', '3720', 'KOREA', ''),
    ('LEE BYUNG HUN', '3721', 'KOREA', ''),
    ('BAE KI NAM', '3722', 'KOREA', ''),
    ('KIM SUNG WOOK', '3727', 'KOREA', ''),
    ('LEE JONG MIN B', '3728', 'KOREA', ''),
    ('LEE SEUNG CHAN', '3729', 'KOREA', ''),
    ('DO HYUN JIN', '3730', 'KOREA', ''),
    ('OH SANG YOUL', '3737', 'KOREA', ''),
    ('JANG JAE YOUNG', '3742', 'KOREA', ''),
    ('KIM DONG HYEOK', '3744', 'KOREA', ''),
    ('LEE JANE', '3748', 'KOREA', ''),
    ('PARK JEONG WOO', '3749', 'KOREA', ''),
    ('LEE IN KI', '3751', 'KOREA', ''),
    ('JUNG HEE SUN', '3752', 'KOREA', ''),
    ('LEE MIN WOOK', '3738', 'KOREA', ''),
    ('SONG JAE MIN', '3756', 'KOREA', ''),
    ('JEON SU A', '3755', 'KOREA', ''),
    ('JEONG JIN WOO', '3757', 'KOREA', ''),
    ('LEE SEUNG JAE C', '3764', 'KOREA', ''),
    ('KIM DEOK HWAN', '3763', 'KOREA', ''),
    ('LEE CHANG HO', '3765', 'KOREA', ''),
    ('KIM YOUNG HAN', '3766', 'KOREA', ''),
    ('KWON SEUNG MIN', '3774', 'KOREA', ''),
    ('CHO BA WUI', '3777', 'KOREA', ''),
    ('PARK JOON HYUNG', '3787', 'KOREA', ''),
    ('YOU SUN JAE', '3786', 'KOREA', ''),
    ('LIM JAE GYU', '3791', 'KOREA', ''),
    ('YOON YEO SUNG', '3792', 'KOREA', ''),
    ('RYU HO HYEON', '3797', 'KOREA', ''),
    ('YU CHAN GUN', '3801', 'KOREA', ''),
    ('MOON YOUNG WOO', '3807', 'KOREA', ''),
    ('KIM SEON JONG', '3806', 'KOREA', ''),
    ('PARK YUN HO', '3803', 'KOREA', ''),
    ('KIM GYEON GRIM', '3804', 'KOREA', ''),
    ('LEE WON ILL', '3805', 'KOREA', ''),
    ('SEO KYU BONG', '3813', 'KOREA', ''),
    ('KIM EUN HYE', '3814', 'KOREA', ''),
    ('LEE YO BIN', '3812', 'KOREA', ''),
    ('JEON DAE EUN', '3811', 'KOREA', ''),
    ('YOON IN A', '3815', 'KOREA', ''),
    ('LEE EUN JOO', '1508', 'KOREA', ''),
    ('KIM HWAN SOO', '3817', 'KOREA', ''),
    ('PARK YU MIN', '3818', 'KOREA', ''),
    ('JUNG DA KYUN', '3820', 'KOREA', ''),
    ('PARK SANG IL', '3821', 'KOREA', ''),
    ('YU YO SUB', '3822', 'KOREA', ''),
    ('CHOI MIN GUK', '3823', 'KOREA', ''),
    ('YOO JOO YOUNG', '3825', 'KOREA', ''),
    ('YANG SEUNG JIN', '3826', 'KOREA', ''),
    ('PARK CHEOL WOO', '3831', 'KOREA', ''),
    ('KANG BUM SUK', '3839', 'KOREA', ''),
    ('YOON DO YEON', '3836', 'KOREA', ''),
    ('LEE KYEONG JAE', '3841', 'KOREA', ''),
    ('JANG SOON KI', '3846', 'KOREA', ''),
    ('LEE MYOUNG SOO', '3850', 'KOREA', ''),
    ('KIM BUM SUK', '3851', 'KOREA', ''),
    ('KIM KYUNG ROK', '3858', 'KOREA', ''),
    ('SHON YEONG TAE', '3860', 'KOREA', ''),
    ('OH DAE HAN', '3861', 'KOREA', ''),
    ('WON JONG MIN', '3864', 'KOREA', ''),
    ('KO JEONG UK', '3862', 'KOREA', ''),
    ('SHIN AH YEONG', '3863', 'KOREA', ''),
    ('HONG JIN POU', '3871', 'KOREA', ''),
    ('LEE HAE ROK', '3872', 'KOREA', ''),
    ('YU SEUNG MIN', '3873', 'KOREA', ''),
    ('KANG WON GYU', '3874', 'KOREA', ''),
    ('PARK CHUL HO', '3888', 'KOREA', ''),
    ('PARK GI HO', '3889', 'KOREA', ''),
    ('KIM KWANG HYUN', '3890', 'KOREA', ''),
    ('JEONG WON DOO', '1567', 'KOREA', ''),
    ('SONG YEONG DU', '3895', 'KOREA', ''),
    ('PARK MIN JE', '3896', 'KOREA', ''),
    ('WON DONG JIN', '3897', 'KOREA', ''),
    ('HAN DO HEON B', '3898', 'KOREA', ''),
    ('OH TAE SEOK', '3899', 'KOREA', ''),
    ('JUNG HUYN SUNG', '3900', 'KOREA', ''),
    ('CHO MIN GI', '3906', 'KOREA', ''),
    ('LEE HU SEON', '3907', 'KOREA', ''),
    ('KIM YU PIN', '3914', 'KOREA', ''),
    ('KO KWAN SUNG', '3915', 'KOREA', ''),
    ('CHOO HO SUK', '3919', 'KOREA', ''),
    ('HER YOUNG JOONG', '3923', 'KOREA', ''),
    ('PYO KYUNG SUB', '3928', 'KOREA', ''),
    ('KIM MIN GYU', '3933', 'KOREA', ''),
    ('PARK SEUNG HEE', '3934', 'KOREA', ''),
    ('CHOI SEUNG HUN', '3932', 'KOREA', ''),
    ('YU GEO NU', '3940', 'KOREA', ''),
    ('YU HYEON U', '3941', 'KOREA', ''),
    ('CHOI YEON SIK', '3942', 'KOREA', ''),
    ('NAM JAE HWANG', '3943', 'KOREA', ''),
    ('KIM HUYNG WOON', '3945', 'KOREA', ''),
    ('LIM IN GEOL', '3946', 'CHINA', ''),
    ('PARK DO WOONG', '3951', 'KOREA', ''),
    ('JANG YOON HO', '3952', 'KOREA', ''),
    ('LIM SEO JIN', '3953', 'KOREA', ''),
    ('PARK SEONG CHEOL', '3954', 'KOREA', ''),
    ('KONG WON UK', '3957', 'KOREA', ''),
    ('PARK SEONG SOO', '3960', 'KOREA', ''),
    ('KIM IN BO', '3963', 'KOREA', ''),
    ('LEE WAN GIL', '3964', 'KOREA', ''),
    ('PARK MIN SOO', '3965', 'KOREA', ''),
    ('KIM KYOUNG JIN', '3968', 'KOREA', ''),
    ('KIM HAN', '3969', 'KOREA', ''),
    ('HEO SE HWAN', '3970', 'KOREA', ''),
    ('YANG SUNG MUN', '3971', 'KOREA', ''),
    ('KIM JUNG CHUL', '3973', 'KOREA', ''),
    ('SIM SO HEE', '3976', 'KOREA', ''),
    ('HONG EUI JO', '3977', 'KOREA', ''),
    ('CHOI SI WOONG', '3980', 'KOREA', ''),
    ('CHO CHANG HEE', '3982', 'KOREA', ''),
    ('LIM DO HYEON', '3983', 'KOREA', ''),
    ('KIM MIN JE', '3984', 'KOREA', ''),
    ('KOOK JEONG HOON', '3985', 'KOREA', ''),
    ('HWANG TEA HO', '3991', 'KOREA', ''),
    ('KWON JUN TAE', '3966', 'KOREA', ''),
    ('LEE HEUNG BUM', '3978', 'KOREA', ''),
    ('KIM DONG HWI', '3993', 'KOREA', ''),
    ('LEE JAE EUN', '3994', 'KOREA', ''),
    ('LEE GYEONG HOON', '3995', 'KOREA', ''),
    ('KANG TAE HYEON', '3997', 'KOREA', ''),
    ('JEONG SANG HWAN', '3998', 'KOREA', ''),
    ('LEE GUN JOO', '4002', 'KOREA', ''),
    ('KANG DONG WON', '4003', 'KOREA', ''),
    ('KWON YOUNG JAE', '4005', 'KOREA', ''),
    ('LEE DOO HWAN', '4006', 'KOREA', ''),
    ('SONG SI WOO', '4016', 'KOREA', ''),
    ('MIN SEOK GWAK', '4017', 'KOREA', ''),
    ('JANG JU SEOK', '4020', 'KOREA', ''),
    ('SIM JEONG HYUN', '4021', 'KOREA', ''),
    ('OH JUN SUK', '4022', 'KOREA', ''),
    ('WI HYEONG SEOK', '4023', 'KOREA', ''),
    ('PARK JU HYEONG', '4025', 'KOREA', ''),
    ('CHOI SUNG HYUK', '4026', 'KOREA', ''),
    ('JEONG JI HUN', '4027', 'KOREA', ''),
    ('KIM JIN SU B', '4028', 'KOREA', ''),
    ('NAM KUN HYUN', '4032', 'KOREA', ''),
    ('LEE JONG HUN', '4035', 'KOREA', ''),
    ('SHIN WOO JIN', '4036', 'KOREA', ''),
    ('JANG WOONG B', '4037', 'KOREA', ''),
    ('KIM MIN WOO', '4038', 'KOREA', ''),
    ('JOENG JOENG SOO', '4039', 'KOREA', ''),
    ('LEE MIN SEOK', '4040', 'KOREA', ''),
    ('SIM SUNG BIN', '4044', 'KOREA', ''),
    ('LEE SEUNG WOOK', '4045', 'KOREA', ''),
    ('LIM JAE WOOK', '4047', 'KOREA', ''),
    ('LEE TAE YANG', '4048', 'KOREA', ''),
    ('HAN JEONG GUNG', '4051', 'KOREA', ''),
    ('KWON DO WON', '3625', 'KOREA', ''),
    ('YU BYEONG HEON', '4052', 'KOREA', ''),
    ('NOH DONG LAK', '4056', 'KOREA', ''),
    ('CHAE JI HUN', '4059', 'KOREA', ''),
    ('HAM SO YOUNG', '4060', 'KOREA', ''),
    ('JUNG SOO IL', '4065', 'KOREA', ''),
    ('SOH HA MIN', '4067', 'KOREA', ''),
    ('LEE DO HA', '4068', 'KOREA', ''),
    ('BYUN WON', '4069', 'KOREA', ''),
    ('YOON JUN YOUNG', '4070', 'KOREA', ''),
    ('CHOI BYUNG GYU', '4072', 'KOREA', ''),
    ('KIM HYO GYUM', '2382', 'KOREA', ''),
    ('CHO DONG KI', '4079', 'KOREA', ''),
    ('HEO SUNG JU', '4077', 'KOREA', ''),
    ('KIM GUN HEE', '4082', 'KOREA', ''),
    ('OH EUN SEONG', '4083', 'KOREA', ''),
    ('JUN WOO TAK', '4084', 'KOREA', ''),
    ('PARK HAN SU', '4085', 'KOREA', ''),
    ('OH SU HWAN', '4086', 'KOREA', ''),
    ('BYUN SUN YONG', '4087', 'KOREA', ''),
    ('KIM BYUNG SOO', '4088', 'KOREA', ''),
    ('AN SUNG WOO', '4089', 'KOREA', ''),
    ('KIM KUN WOO', '4090', 'KOREA', ''),
    ('MOON JUNG JIN', '4093', 'KOREA', ''),
    ('LEE MOON YONG', '4094', 'KOREA', ''),
    ('KWON OH HYOUNG', '4096', 'KOREA', ''),
    ('PARK YOUNG JIN', '4097', 'KOREA', ''),
    ('JIN SUN MIN', '4100', 'KOREA', ''),
    ('JEON SI HEON', '4102', 'KOREA', ''),
    ('PARK SUNG EUN', '4103', 'KOREA', ''),
    ('NOH JAE PILL', '4105', 'KOREA', ''),
    ('CHOE SEUNG ON', '4107', 'KOREA', ''),
    ('JANG SEUNG HEON', '4109', 'KOREA', ''),
    ('JEON HYE SUNG', '4110', 'KOREA', ''),
    ('KIM JIM IN', '4111', 'KOREA', ''),
    ('YOUNG SU YU', '398', 'KOREA', ''),
    ('KIM YOUNG DO', '4119', 'KOREA', ''),
    ('KYEONG DAL JANG', '4121', 'KOREA', ''),
    ('CHUN KYEONG IN', '4123', 'KOREA', ''),
    ('HEO KWAN GIL', '4124', 'KOREA', ''),
    ('JUN SEOK KIM', '4127', 'KOREA', ''),
    ('LEE YONG SUNG', '4132', 'KOREA', ''),
    ('LEE JONG WON B', '4139', 'KOREA', ''),
    ('YANG JAE HAK', '4140', 'KOREA', ''),
    ('KIM JAE YOON', '4141', 'KOREA', ''),
    ('KIM SUNG JOON', '4145', 'KOREA', ''),
    ('KIM HUYN SOO', '4147', 'KOREA', ''),
    ('KIM HYO HUN', '4148', 'KOREA', ''),
    ('LIM JEONG SEOB', '4149', 'KOREA', ''),
    ('KIM UN JUNG', '2761', 'KOREA', ''),
    ('PARK IL SEOK', '2762', 'KOREA', ''),
    ('YU MYEONG KYUN', '2764', 'KOREA', ''),
    ('CHOI YOUNG JUN B', '2765', 'KOREA', ''),
    ('KANG YONG CHAN', '2766', 'KOREA', ''),
    ('HWANG SEUNG UK', '2767', 'KOREA', ''),
    ('JO MIN SU', '2768', 'KOREA', ''),
    ('KIM WOO SUK', '2770', 'KOREA', ''),
    ('BAEK JONG HUN', '2773', 'KOREA', ''),
    ('LEE CHEOL WOO', '2776', 'KOREA', ''),
    ('KWON KYUNG YEOL', '2777', 'KOREA', ''),
    ('LEE SI ON', '2778', 'KOREA', ''),
    ('IM YOUNG DAE', '2779', 'KOREA', ''),
    ('JUNG DA BIN', '2781', 'KOREA', ''),
    ('LEE DUCK KWANG', '2782', 'KOREA', ''),
    ('LEE SEO HYUN', '2816', 'KOREA', ''),
    ('PARK JAE HYUNG', '2793', 'KOREA', ''),
    ('LEE HUN JANG', '2790', 'KOREA', ''),
    ('YOO SUN HO', '2811', 'KOREA', ''),
    ('KIM A YOUNG', '2807', 'KOREA', ''),
    ('PARK MIN SOO', '2808', 'KOREA', ''),
    ('AN SANG WOO', '2804', 'KOREA', ''),
    ('KIM TAE HYEONG', '2795', 'KOREA', ''),
    ('LEE JUNG HYUN', '2801', 'KOREA', ''),
    ('SONG MYUNG KEUN', '2787', 'KOREA', ''),
    ('JUNG YOUNG CHUL', '2785', 'KOREA', ''),
    ('JANG SU MIN', '2818', 'KOREA', ''),
    ('LEE JU HEE', '2817', 'KOREA', ''),
    ('LEE SEUNG HOON', '2796', 'KOREA', ''),
    ('LEE CHANG HAN', '2797', 'KOREA', ''),
    ('PARK JOONG KWAN', '2799', 'KOREA', ''),
    ('PARK JUN KYU', '2820', 'KOREA', ''),
    ('JEONG DU JIN', '2821', 'KOREA', ''),
    ('KIM SEOK WON', '2823', 'KOREA', ''),
    ('LEE JONG JUN', '2826', 'KOREA', ''),
    ('PARK MIN HYO', '2825', 'KOREA', ''),
    ('OH JUN SEOK', '2824', 'KOREA', ''),
    ('JUNG HWANG HEE', '2828', 'KOREA', ''),
    ('JUNG HWI GUN', '2827', 'KOREA', ''),
    ('HWANG JEONG HOON', '2829', 'KOREA', ''),
    ('KIM EUN JIN', '2834', 'KOREA', ''),
    ('SONG CHANG WON', '2833', 'KOREA', ''),
    ('JANG GYU WON', '2832', 'KOREA', ''),
    ('LEE MYEONG HO', '2837', 'KOREA', ''),
    ('BAE SANG YOON', '2839', 'KOREA', ''),
    ('BAE JU HWAN', '2840', 'KOREA', ''),
    ('LEE SANG YEON', '2841', 'KOREA', ''),
    ('KIM HYUN WOO', '2842', 'KOREA', ''),
    ('LEE MYEONG SOO', '2844', 'KOREA', ''),
    ('LEE JU HYEON', '2849', 'KOREA', ''),
    ('JUNG GA HUN', '2850', 'KOREA', ''),
    ('SIM EUN JUNG', '2851', 'KOREA', ''),
    ('JUNG SANG JUN', '2862', 'KOREA', ''),
    ('CHOI MIN CHEOL', '2866', 'KOREA', ''),
    ('RYU SEONG HEON', '2861', 'KOREA', ''),
    ('LEE KWANG SOO', '2860', 'KOREA', ''),
    ('SEO SUNG HUN', '2713', 'KOREA', ''),
    ('LIM DONG HYUN', '2715', 'KOREA', ''),
    ('KIM YOUNG SEOK', '2856', 'KOREA', ''),
    ('JEON GYEONG SEOK', '2859', 'KOREA', ''),
    ('KWAK MIN SEUNG', '2858', 'KOREA', ''),
    ('KONG DONG HO', '2863', 'KOREA', ''),
    ('HWANG YEON SO', '2862', 'KOREA', ''),
    ('KIM DO A', '2881', 'KOREA', ''),
    ('BAEK IL JO', '2880', 'KOREA', ''),
    ('JEONG YU RYANG', '2878', 'KOREA', ''),
    ('KIM JONG MIN', '2876', 'KOREA', ''),
    ('CHOI WOO SUNG', '2877', 'KOREA', ''),
    ('KIM BYUNG HOON(재)', '2875', 'KOREA', ''),
    ('NAM GUNG SEOK', '2874', 'KOREA', ''),
    ('LEE HEON GOO', '2873', 'KOREA', ''),
    ('KIM HYUN SU', '2871', 'KOREA', ''),
    ('LEE CHANG HWAN', '2869', 'KOREA', ''),
    ('LEE CHANG JUN', '2868', 'KOREA', ''),
    ('KIM HONG SEOK', '2885', 'KOREA', ''),
    ('LEE KYE WON', '2886', 'KOREA', ''),
    ('CHOI HA SEON', '2887', 'KOREA', ''),
    ('SEO JUN SUK', '2888', 'KOREA', ''),
    ('KIM SE JONG', '2889(재발급)', 'KOREA', ''),
    ('JANG DONG HEE', '2893', 'KOREA', ''),
    ('JANG HO MOON', '2894', 'KOREA', ''),
    ('KIM SANG YOON', '2895', 'KOREA', ''),
    ('BAEK SEUNG HYEOB', '2896', 'KOREA', ''),
    ('KANG HYE RI', '2897', 'KOREA', ''),
    ('HAN HEE JIN', '2898', 'KOREA', ''),
    ('PARK JUNG SEEK', '2899', 'KOREA', ''),
    ('KIM SANG HO', '2937', 'KOREA', ''),
    ('PARK HAN UL', '2936', 'KOREA', ''),
    ('PARK MIN JI', '2935', 'KOREA', ''),
    ('LEE JAE YONG', '2939', 'KOREA', ''),
    ('LEE JUNG YEOB', '2933', 'KOREA', ''),
    ('YOO JAE PIL', '2929', 'KOREA', ''),
    ('LEE JAE HAK', '2931', 'KOREA', ''),
    ('KIM SEA YEON', '2930', 'KOREA', ''),
    ('CHOI DAE SIK', '2737', 'KOREA', ''),
    ('LEE MYEONG SEONG', '2910', 'KOREA', ''),
    ('HA JI HWAN', '2911', 'KOREA', ''),
    ('KIM MIN KYU', '2912', 'KOREA', ''),
    ('YOON SEOK MIN', '2913', 'KOREA', ''),
    ('PARK JI YOUNG', '2914', 'KOREA', ''),
    ('PARK YOUNG IL', '1325', 'KOREA', ''),
    ('YEOM KWANG BOK', '2918', 'KOREA', ''),
    ('CHUN HWA HYEON', '2919', 'KOREA', ''),
    ('PARK YOUNG CHUN', '2920', 'KOREA', ''),
    ('KIM MIN JUN', '2921', 'KOREA', ''),
    ('KIM HYEON MIN', '2922', 'KOREA', ''),
    ('YOO HONG GO', '2923', 'KOREA', ''),
    ('CHOI HYUN YOUL', '2924', 'KOREA', ''),
    ('JIN JONG HYUN', '2916', 'KOREA', ''),
    ('KANG MO SE', '2915', 'KOREA', ''),
    ('GWAK SE HONG', '2925', 'KOREA', ''),
    ('HWANG SEOK JIN', '2909', 'KOREA', ''),
    ('JUNG SUNG HUI', '2908', 'KOREA', ''),
    ('CHOI SEUNG HOON', '2907', 'KOREA', ''),
    ('YIM SANG WOOK', '2906', 'KOREA', ''),
    ('CHOI JAE BONG', '2905', 'KOREA', ''),
    ('CHO IN HYO', '2904', 'KOREA', ''),
    ('GYEONG BYEONG LEE', '2903', 'KOREA', ''),
    ('KIM TAE HWAN', '2902', 'KOREA', ''),
    ('CHOI JONG WON', '2900', 'KOREA', ''),
    ('KIM WON HYEONG', '2940', 'KOREA', ''),
    ('YOON SANG YONG', '2928', 'KOREA', ''),
    ('CHO HANG DUK', '2927', 'KOREA', ''),
    ('NAM KI CHUL', '2941', 'KOREA', ''),
    ('KIM TAE RI', '2942', 'KOREA', ''),
    ('KIM IL JUNG', '2932', 'KOREA', ''),
    ('LEE JU HEON', '2969', 'KOREA', ''),
    ('YUN HAE JU', '2968', 'KOREA', ''),
    ('YUN JUN HYEOK', '2963', 'KOREA', ''),
    ('KIM HYEON DO', '2964', 'KOREA', ''),
    ('KO KYUNG SUK', '2946', 'KOREA', ''),
    ('YOO JI HO', '2947', 'KOREA', ''),
    ('HWI GON PARK', '2948', 'KOREA', ''),
    ('YEON SEO YU', '2953', 'KOREA', ''),
    ('KIM GAP DONG', '2952', 'KOREA', ''),
    ('LEE JUN GI', '2954', 'KOREA', ''),
    ('KIM SEONG GWON', '2957', 'KOREA', ''),
    ('LEE EUN SUNG', '2958', 'KOREA', ''),
    ('SEO CHUN HO', '2733', 'KOREA', ''),
    ('KIM GEE HONG', '2959', 'KOREA', ''),
    ('CHOI GWANG HO', '2961', 'KOREA', ''),
    ('PARK JIN KWAN', '2962', 'KOREA', ''),
    ('JANG JUN YONG', '2960', 'KOREA', ''),
    ('BAE CHANG UK', '2967', 'KOREA', ''),
    ('KIM HYEON DO', '2964', 'KOREA', ''),
    ('YUN JUN HYEOK', '2963', 'KOREA', ''),
    ('YUN HAE JU', '2968', 'KOREA', ''),
    ('LEE JU HEON', '2969', 'KOREA', ''),
    ('LEE MYEONG GYU', '2978', 'KOREA', ''),
    ('KIM TAE WAN', '2979', 'KOREA', ''),
    ('KIM IN KYOUNG', '2980', 'KOREA', ''),
    ('PARK GWANG MIN', '2981', 'KOREA', ''),
    ('KIM KYUNG MIN', '2983', 'KOREA', ''),
    ('SEO MIN GI', '2986', 'KOREA', ''),
    ('YOO SANG WON', '2987', 'KOREA', ''),
    ('KIM EUN SOOK', '2988', 'KOREA', ''),
    ('AHN SEONG HUN', '2989', 'KOREA', ''),
    ('KIM JEONG HYUN', '2992', 'KOREA', ''),
    ('LEE JING WON', '2993', 'KOREA', ''),
    ('PAK SEOK WON', '2997', 'KOREA', ''),
    ('LEE MOON KYO', '2998', 'KOREA', ''),
    ('LEE HYUNG MO', '2999', 'KOREA', ''),
    ('KIM JONG WOO', '3001', 'KOREA', ''),
    ('LEE AN NA', '3003', 'KOREA', ''),
    ('HAN SEUNG HYUK', '3007', 'KOREA', ''),
    ('LEE JOO YOUNG', '3008', 'KOREA', ''),
    ('SEO SANG WOO', '3013', 'KOREA', ''),
    ('JONG JIN SU', '3010', 'KOREA', ''),
    ('KIM DONG MIN', '3014', 'KOREA', ''),
    ('JANG WON HEUN', '3015', 'KOREA', ''),
    ('PARK SEUL KI', '3016', 'KOREA', ''),
    ('YONG SEOK KWON', '3017', 'KOREA', ''),
    ('AN SEUNG HYEOK', '3018', 'KOREA', ''),
    ('SEO MUN KYO', '3022', 'KOREA', ''),
    ('JUNG EUI TAEK', '3023', 'KOREA', ''),
    ('HWANG SEONG HO', '3029', 'KOREA', ''),
    ('CHOI JUNG MIN', '3027', 'KOREA', ''),
    ('KIM NA KYOUNG', '3021', 'KOREA', ''),
    ('LEE HYUN MIN', '3025', 'KOREA', ''),
    ('KIM JWA JIN', '3026', 'KOREA', ''),
    ('OH SEOK JUN', '3024', 'KOREA', ''),
    ('KIM JU HYUN', '3032', 'KOREA', ''),
    ('CHOI JUN YEONG', '3041', 'KOREA', ''),
    ('PARK JEONG HO', '3034', 'KOREA', ''),
    ('LEE WON MIN', '3042', 'KOREA', ''),
    ('PARK JIN WOO', '3043', 'KOREA', ''),
    ('KANG JIN HO', '3038', 'KOREA', ''),
    ('CHOI HYUN SEOK', '3046', 'KOREA', ''),
    ('KIM MIN HEE', '3045', 'KOREA', ''),
    ('PARK SANG SUB', '3044', 'KOREA', ''),
    ('LIM CHAE HWAN', '3041', 'KOREA', ''),
    ('LIM WON JUN', '3040', 'KOREA', ''),
    ('JANG MUN SUNG', '3039', 'KOREA', ''),
    ('HONG SEONG JIN', '3036', 'KOREA', ''),
    ('PARK DA JUNG', '3037', 'KOREA', ''),
    ('KIM MIN CHAN', '3050', 'KOREA', ''),
    ('PARK JU JUNG', '1691', 'KOREA', ''),
    ('KANG BYEONG HUI', '', 'KOREA', ''),
    ('JEONG IN HWA', '', 'KOREA', ''),
    ('HONG MYEONG GI', '478', 'KOREA', ''),
    ('PHAM NHAT AN', '', 'KOREA', ''),
    ('JIN HYO YOO', '', 'KOREA', ''),
    ('KIM DAE YOUNG', '', 'KOREA', ''),
    ('CHOI KWANG GUK', '', 'KOREA', ''),
    ('HAN SUNG IL', '', 'KOREA', ''),
    ('JIN', '465', 'KOREA', ''),
    ('PARK WON SEOK', '432', 'KOREA', ''),
    ('LEE SANG MIN', '', 'KOREA', ''),
    ('LEE MIN WOO', '', 'KOREA', ''),
    ('LEE TAE JUN', '', 'KOREA', ''),
    ('YOU SUN TE', '', 'KOREA', ''),
    ('CHOI DUE HYUN', '', 'KOREA', ''),
    ('LEE SEOK YOUNG', '', 'KOREA', ''),
    ('KIM JONG RAE', '', 'KOREA', ''),
    ('PARK SAN HAE', '', 'KOREA', ''),
    ('JOUNG HA GUEN', '', 'KOREA', ''),
    ('LEE KOANG HO', '', 'KOREA', ''),
    ('MAENG SANG KYO', '', 'KOREA', ''),
    ('CHO HANG JUN', '', 'KOREA', ''),
    ('PARK JAE RIM', '', 'KOREA', ''),
    ('CHO DAE HEE', '', 'KOREA', ''),
    ('LEE IN JEONG', '', 'KOREA', ''),
    ('KANG HOON', '', 'KOREA', ''),
    ('KIM JUNG WON', '', 'KOREA', ''),
    ('JIN SUNG MIN', '542', 'KOREA', ''),
    ('AN HO EUNG', '480', 'KOREA', ''),
    ('CHOI YEONG CHAN', '', 'KOREA', ''),
    ('AHN WOO SUNG', '', 'KOREA', ''),
    ('PANSOY CHARLES ED', '', 'KOREA', ''),
    ('KIM CHUL YONG', '450', 'KOREA', ''),
    ('LUCAS ANTONIO DA ROSS LOPES', '', 'KOREA', ''),
    ('LEE SUNG HOON', '', 'KOREA', ''),
    ('JO GIL SANG', '', 'KOREA', ''),
    ('KIM SUNG HOON', '', 'KOREA', ''),
    ('SONG KI TAG', '', 'KOREA', ''),
    ('LEE JONG GU', '', 'KOREA', ''),
    ('JUNG JAE MIN', '', 'KOREA', ''),
    ('CHOI JUNG HWAN', '', 'KOREA', ''),
    ('HAN KEON WOONG', '', 'KOREA', ''),
    ('KIM DA HUN', '', 'KOREA', ''),
    ('PARK JUN SILK', '', 'KOREA', ''),
    ('JEON SO MIN', '', 'KOREA', ''),
    ('OH YOUNG KEUN', '', 'KOREA', ''),
    ('SEO SEUNG HUN', '', 'KOREA', ''),
    ('KIM SU NIL', '', 'KOREA', ''),
    ('KIM JUNG SU', '', 'KOREA', ''),
    ('KIM EUN MAN', '', 'KOREA', ''),
    ('JANG JONG BEA', '1054', 'KOREA', ''),
    ('LEE JAE SU', '1539', 'KOREA', ''),
    ('LEE HYUN JOO', '', 'KOREA', ''),
    ('YONG SOO HAN', '', 'KOREA', ''),
    ('YOU HEUNG YOUL', '', 'KOREA', ''),
    ('JIN BYUNG WAN', '', 'KOREA', ''),
    ('KIM DO YEON', '', 'KOREA', ''),
    ('KIM JAE HYUNG', '', 'KOREA', ''),
    ('MOON SANG SUK', '', 'KOREA', ''),
    ('KIM JOO HYUN', '', 'KOREA', ''),
    ('HWANG HYE MIN', '', 'KOREA', ''),
    ('KIM YE RIM', '', 'KOREA', ''),
    ('JANG WO NIL', '', 'KOREA', ''),
    ('LEE SANG WOO (B)', '', 'KOREA', ''),
    ('HA SEUNG CHAN', '', 'KOREA', ''),
    ('LEE HWA JUN', '1366', 'KOREA', ''),
    ('LEE KANG MIN', '', 'KOREA', ''),
    ('KIM HONG PYO', '', 'KOREA', ''),
    ('YU CHANG WOO', '', 'KOREA', ''),
    ('KANG SHI NIL', '', 'KOREA', ''),
    ('KIM HYUN TAE', '', 'KOREA', ''),
    ('SIM WOO TAK', '', 'KOREA', ''),
    ('JUNG EUI HYUN', '', 'KOREA', ''),
    ('LEE DONG GYU', '', 'KOREA', ''),
    ('HAN SANG DUCK', '', 'KOREA', ''),
    ('JO YONG MUN', '', 'KOREA', ''),
    ('ANN JEA MEAN', '2938', 'KOREA', ''),
    ('PARK KYOUNG WON', '', 'KOREA', ''),
    ('KIM JAE KOOK', '', 'KOREA', ''),
    ('CHA YUN WOO', '', 'KOREA', ''),
    ('PARK SANG KOOK', '1758', 'KOREA', ''),
    ('LI JIN MING', '', 'KOREA', ''),
    ('PARK MIN JUNG', '', 'KOREA', ''),
    ('JI CHUN', '', 'KOREA', ''),
    ('KIM MIN YOUNG', '', 'KOREA', ''),
    ('KIM SUN IL', '', 'KOREA', ''),
    ('JUNG WON SEOK', '', 'KOREA', ''),
    ('HWANG WHUI YEONG', '', 'KOREA', ''),
    ('KWON OH YOUNG', '1614', 'KOREA', ''),
    ('YEO SAN', '', 'KOREA', ''),
    ('YOO WON JUNG', '', 'KOREA', ''),
    ('KANG DONG HUN', '', 'KOREA', ''),
    ('KIM DAE HWAN', '', 'KOREA', ''),
    ('AHN JAE MIN', '', 'KOREA', ''),
    ('LEE JI MIN', '514', 'KOREA', ''),
    ('LEE HONG RYE', '', 'KOREA', '하노이로 가심'),
    ('JANG EUN SANG', '1797', 'KOREA', ''),
    ('JEONG JONG SEONG', '', 'KOREA', ''),
    ('KIM MIN', '', 'KOREA', ''),
    ('GAL YOO SEUNG', '', 'KOREA', ''),
    ('KIM MIN SEONG', '', 'KOREA', ''),
    ('KIM HAE WON', '404', 'KOREA', ''),
    ('LUCKY 6868', '', 'KOREA', ''),
    ('KIM YOUNH JUN', '', 'KOREA', ''),
    ('BAEK JAE HO', '', 'KOREA', ''),
    ('KIM SIN AE', '', 'KOREA', ''),
    ('LEE SEUNG WON', '', 'KOREA', ''),
    ('HA SUNG MIN', '', 'KOREA', ''),
    ('CHOI JIN WOO', '', 'KOREA', ''),
    ('KIM CHANG JUN', '', 'KOREA', ''),
    ('YOO EUN JUNG', '', 'KOREA', ''),
    ('UM JI EUN', '', 'KOREA', ''),
    ('SHIN JAE WOOK', '', 'KOREA', ''),
    ('LIM YOH WAN', '', 'KOREA', ''),
    ('KANG DONG JIN', '', 'KOREA', ''),
    ('KIM JIN SUNG', '', 'KOREA', ''),
    ('GU JU WAN', '', 'KOREA', ''),
    ('KIM DO HYEONG', '', 'KOREA', ''),
    ('LEE TA NA', '', 'KOREA', ''),
    ('SEO JEONG CHUN', '', 'KOREA', ''),
    ('KWON HYUCK PYO', '', 'KOREA', ''),
    ('KIM SE WOOK', '1739', 'KOREA', ''),
    ('KIM JANG HOON', '', 'KOREA', ''),
    ('JU SUNG UK', '481', 'KOREA', ''),
    ('LEE HONG RYE', '', 'KOREA', ''),
    ('KIM SEONG HOON', '', 'KOREA', ''),
    ('JOO YOUNG SU', '', 'KOREA', ''),
    ('LUCKY', '117', 'KOREA', ''),
    ('PARK JAE RIM', '', 'KOREA', ''),
    ('KIM SE JONG', '', 'KOREA', ''),
    ('YANG HOON MIN', '', 'KOREA', ''),
    ('KIM DO YEON', '', 'KOREA', ''),
    ('KANG HYUN WOO', '', 'KOREA', ''),
    ('PARK KEON WOO', '', 'KOREA', ''),
    ('PARK KYOUNG WON', '', 'KOREA', ''),
    ('WOO JONG YUL', '1514', 'KOREA', ''),
    ('LEE JI WON', '4158', 'KOREA', ''),
    ('PARK JAE WON', '4159', 'KOREA', ''),
    ('KIM HYEONG YUL', '4160', 'KOREA', ''),
    ('KIM HAE YOUNG', '4162', 'KOREA', ''),
    ('OH SEUNG MIN', '4164', 'KOREA', ''),
    ('OH DAE SUK', '4167', 'KOREA', ''),
    ('KIM KANG RIN', '4168', 'KOREA', ''),
    ('PARK JIN MAN', '4169', 'KOREA', ''),
    ('KIM JEONG GON', '4170', 'KOREA', ''),
    ('KIM SUNG JOO', '4172', 'KOREA', ''),
    ('KIM AN NA', '4173', 'KOREA', ''),
    ('YANG JENG MO', '1718', 'KOREA', ''),
    ('KIM YOUNG JUN', '262', 'KOREA', ''),
    ('JUN YOUNG YOON', '', 'KOREA', ''),
    ('MA SANG HYO', '4174', 'KOREA', ''),
    ('CHOI YOUNG GYU', '4176', 'KOREA', ''),
    ('YOO JIN HYO', '571', 'KOREA', ''),
    ('LEE JINHO', '4179', 'KOREA', ''),
    ('PARK JAEHYUN', '4180', 'KOREA', ''),
    ('UM TAEHYUN', '4181', 'KOREA', ''),
    ('LEE CHANGHYUN', '4182', 'KOREA', ''),
    ('DOO SOAN', '4184', 'KOREA', ''),
    ('LEE TAE HEE', '4189', 'KOREA', ''),
    ('KIM HYEONG JUNG', '1585', 'KOREA', ''),
    ('KIM JIN WAN', '', 'KOREA', ''),
    ('OH KI TAE', '110', 'KOREA', ''),
    ('SUNG WOO YOUNG', '4203', 'KOREA', ''),
    ('KIM DA BIN', '938', 'KOREA', ''),
    ('PARK SU HWA', '4206', 'KOREA', ''),
    ('KIM PYEONG KANG', '4216', 'KOREA', ''),
    ('KWON SOON WOOK', '4217', 'KOREA', ''),
    ('LIM DONG WANG', '4219', 'KOREA', ''),
    ('JO TAE IK', '4225', 'KOREA', ''),
    ('LEE HAN YONG', '4226', 'KOREA', ''),
    ('LIM DONG KYUN', '4227', 'KOREA', ''),
    ('JUNG YOON GU', '4228', 'KOREA', ''),
    ('KIM CHAE YEON', '4237', 'KOREA', ''),
    ('YANG JAE YUN', '4240', 'KOREA', ''),
    ('LEE TAE GON', '4241', 'KOREA', ''),
    ('KIM HYUN JIN', '1568', 'KOREA', ''),
    ('KIM JI HUN', '4248', 'KOREA', ''),
    ('KIM KUN ROK', '4249', 'KOREA', ''),
    ('LEE JI HO', '4245', 'KOREA', ''),
    ('LEE TAE HYUNG', '4244', 'KOREA', ''),
    ('EO JIN SEON', '4247', 'KOREA', ''),
    ('LEE JUN HEE', '4251', 'KOREA', ''),
    ('LEE SE KYU', '4256', 'KOREA', ''),
    ('KIM KYUM', '4266', 'KOREA', ''),
    ('LEE JI HOON', '1941', 'KOREA', ''),
    ('JEON MIN HYEOK', '4276', 'KOREA', ''),
    ('LEE WON BUM', '4277', 'KOREA', ''),
    ('JANG JI SAN', '4278', 'KOREA', ''),
    ('LEE JEONG JU', '4279', 'KOREA', ''),
    ('BEAK HYEON', '526', 'KOREA', ''),
    ('RYU SANG WOOK', '4284', 'KOREA', ''),
    ('HAN DONG YOON', '4283', 'KOREA', ''),
    ('JEON CHANG BUM', '4281', 'KOREA', ''),
    ('CHOE JEONG YEOL', '4288', 'KOREA', ''),
    ('NAM HYUNG SIK', '4290', 'KOREA', ''),
    ('KIM SUNG SU', '2601', 'KOREA', ''),
    ('KIM GA YOUNG', '4295', 'KOREA', ''),
    ('GU DO KYUN', '1696', 'KOREA', ''),
    ('JO HOON HEE', '4312', 'KOREA', ''),
    ('CHOI SEUNG HWAN', '2312', 'KOREA', ''),
    ('OH SOON CHUN', '4314', 'KOREA', ''),
    ('SEO KYUNG IL', '4313', 'KOREA', ''),
    ('NAM JUNG GEUN', '4332', 'KOREA', '1/11'),
    ('KIM GI HYEON', '4319', 'KOREA', ''),
    ('PARK CHAN SUN', '4321', 'KOREA', ''),
    ('KIM SUNG MIN', '2435', 'KOREA', ''),
    ('CHO DA RAM', '1362', 'KOREA', ''),
    ('LEE DONG HYUN', '4323', 'KOREA', ''),
    ('LEE JAE MAN', '4322', 'KOREA', ''),
    ('MUN MYUNG HO', '4325', 'KOREA', ''),
    ('CHOI MYUNNG IL', '4326', 'KOREA', ''),
    ('CHOI JAE HOON', '4327', 'KOREA', ''),
    ('KIM CHANG IL', '4328', 'KOREA', ''),
    ('JANG KI BONG', '4329', 'KOREA', ''),
    ('LEE JUNG CHUL', '4330', 'KOREA', ''),
    ('CHOI KONG HUN', '4342', 'KOREA', '1/12'),
    ('PARK SANG IN', '229', 'KOREA', ''),
    ('LEE GYEONG JUN', '4286', 'KOREA', ''),
    ('AN JAE BUM', '4346', 'KOREA', '1/13'),
    ('PARK YEONG GEOL', '4349', 'KOREA', ''),
    ('LEE HYUN DONG', '4350', 'KOREA', ''),
    ('JUNG SUNG HWAN', '4361', 'KOREA', '1/14'),
    ('MOON JOONG HYUN', '4363', 'KOREA', ''),
    ('YOON YOUNG SEO', '4366', 'KOREA', ''),
    ('HWANG SUN WOO', '4367', 'KOREA', ''),
    ('KIM SUNG HYEON', '4372', 'KOREA', ''),
    ('KIM CHAN JOONG', '522', 'KOREA', '1'),
    ('YANG HYUN WOO', '4057', 'KOREA', ''),
    ('YANG KYUNG TAE', '4375', 'KOREA', '1/15'),
    ('SONG HYEON GYU', '4376', 'KOREA', ''),
    ('CHOI YOUNG SU', '4377', 'KOREA', ''),
    ('XU CHANG YAN', '2892', 'CHINA', ''),
    ('CHEN HUI B', '4208', 'CHINA', ''),
    ('YU YONG YI', '1229', 'CHINA', '1/16'),
    ('SUN CHONG FENG', '3052', 'CHINA', ''),
    ('JIN XUE FAN', '4259', 'CHINA', ''),
    ('CUI ZI CHUN', '674', 'CHINA', ''),
    ('HUNG CHUAN CHIA', '4370', 'CHINA', ''),
    ('WANG CHEN LU', '1304', 'CHINA', ''),
    ('BEAK JONG UK', '4387', 'KOREA', ''),
    ('YOO HEE CHAN', '4390', 'KOREA', ''),
    ('KIM MIN JAE', '4389', 'KOREA', ''),
    ('LEE SEONG UK', '4388', 'KOREA', ''),
    ('KO YOUNG MUN', '228', 'KOREA', ''),
    ('LEE CHUL HAENG', '4378', 'KOREA', ''),
    ('YUAN YANG', '4014', 'CHINA', ''),
    ('WU PING', '1192', 'CHINA', ''),
    ('YE NING', '3944', 'CHINA', ''),
    ('WANG HONGRUI', '3950', 'CHINA', ''),
    ('KIM HUN SU', '4399', 'KOREA', '1/17'),
    ('YANG TIAN JUN', '3429', 'CHINA', ''),
    ('YE GUI CAI', '1402', 'CHINA', ''),
    ('JIANG XIAO MING', '1218', 'CHINA', ''),
    ('LI MING', '2297', 'CHINA', ''),
    ('ZHANG LIE', '1980', 'CHINA', ''),
    ('KIM JI YOUNG', '4146', 'HOUSE', ''),
    ('SHIN SEONG HEON', '4405', 'KOREA', '1/18'),
    ('LIN YUE', '4354', 'CHINA', ''),
    ('ZHAO GUANG YU', '4150', 'CHINA', ''),
    ('YUN SANG WOO', '4407', 'KOREA', '1/19'),
    ('MAENG JI TAE', '4409', 'KOREA', ''),
    ('JUNG JAE IN', '4408', 'KOREA', ''),
    ('PARK YOUNG WOOK', '4411', 'KOREA', ''),
    ('TAKESHI NAKABAYASHI', '4410', 'JAPAN', ''),
    ('PARK IN PYO', '4413', 'KOREA', ''),
    ('PARK JONG HYEON', '4416', 'KOREA', ''),
    ('AHN YU SEOP', '4418', 'KOREA', ''),
    ('KIM YOUNG EUN', '4419', 'KOREA', ''),
    ('LEE KWANG TAE', '4425', 'KOREA', ''),
    ('ZHANG YIN LING', '4415', 'CHINA', ''),
    ('LIM ZHEN', '4420', 'CHINA', ''),
    ('LOU JING LIN', '4421', 'CHINA', ''),
    ('RANG TAE WOOK', '4429', 'KOREA', ''),
    ('EOM JI HOON', '4428', 'KOREA', ''),
    ('LEE JAE UNG', '4430', 'KOREA', ''),
    ('PARK SEONG JUN', '4431', 'KOREA', '1/20'),
    ('NOH GEON YONG', '4432', 'KOREA', ''),
    ('SHIN SUNG BUM', '4433', 'KOREA', ''),
    ('JEONG YE RIM', '4437', 'KOREA', ''),
    ('KWON HUI YUN', '4438', 'KOREA', ''),
    ('JUNG DA BIN B', '4440', 'KOREA', ''),
    ('KIM SUNG JOO B', '4439', 'KOREA', ''),
    ('LEE SUNG ILL', '4427', 'KOREA', ''),
    ('KIM YONG SEOK', '4443', 'KOREA', '1/21'),
    ('JEONG YONG JAE', '4454', 'KOREA', '1/22'),
    ('KIM BU SU', '4461', 'KOREA', ''),
    ('PARK KYUNG WOO', '4458', 'KOREA', ''),
    ('YOO I HYUN', '4470', 'KOREA', ''),
    ('CHUNG TAE SUNG', '4471', 'KOREA', ''),
    ('BYUN JAE WON', '4455', 'KOREA', ''),
    ('MOON SO YEON', '4456', 'KOREA', ''),
    ('PARK ESTHER', '4459', 'KOREA', ''),
    ('KIM BO SEONG', '4460', 'KOREA', ''),
    ('JUNG YU JIN', '4462', 'KOREA', ''),
    ('KIM JUM GYU', '4478', 'KOREA', ''),
    ('OH SANG HOON', '4479', 'KOREA', ''),
    ('KANG GYEONG MIN', '4488', 'KOREA', '1/23'),
    ('JEONG JUN HWA', '4490', 'KOREA', ''),
    ('KANG DONG HYO', '4489', 'KOREA', ''),
    ('SHIN HYUNG JU', '4495', 'KOREA', '1/24'),
    ('CARAGAY CARLO JAMIL', '', 'PHILIPPINES', ''),
    ('ARMAUIDO P CABARDO', '', 'PHILIPPINES', ''),
    ('ALAN JAMES YAP', '', 'PHILIPPINES', ''),
    ('PARK JOO HYUN', '', 'HOUSE', ''),
    ('PARK HEE NAM', '', 'KOREA', ''),
    ('KIM YONG SUNG', '', 'KOREA', ''),
    ('KIM CHAN HO', '', 'KOREA', ''),
    ('YANG JUN YOUNG', '', 'KOREA', ''),
    ('YOON TAE HYUN', '', 'KOREA', ''),
    ('PARK JIN YEONG', '', 'KOREA', ''),
    ('KIM CHAN HO', '', 'KOREA', ''),
    ('KIM HAN SANG', '', 'KOREA', ''),
    ('OH HYO SUK', '', 'KOREA', ''),
    ('PARK SUNG BOK', '', 'KOREA', ''),
    ('KIM SANG MUK', '', 'KOREA', ''),
    ('KIM YONG SEON', '', 'KOREA', ''),
    ('KWON WON CHUL', '', 'KOREA', ''),
    ('SHIN CHI HOON', '', 'HOUSE', ''),
    ('KIM TAE SU', '', 'KOREA', ''),
    ('SHIN MIN HO', '', 'KOREA', ''),
    ('CHENG CHAO', '', 'CHINA', ''),
    ('KEVIN', '', 'FRANCE', 'FRANCE'),
    ('NUESTRO JUNE BRIX', '', 'PHILIPPINES', 'PHILIPPINES'),
    ('OH SEONG JUN', '', 'KOREA', ''),
    ('ZHANG YU', '', 'CHINA', ''),
    ('SHI JIAN', '', 'CHINA', ''),
    ('LI XIAOBO', '', 'CHINA', ''),
    ('JI JIE', '', 'CHINA', ''),
    ('KIM YEON DEUG', '', 'KOREA', ''),
    ('MOON CHO ROK', '', 'KOREA', ''),
    ('GIM JAE YOUNG', '', 'KOREA', ''),
    ('SHIN JEONG WOO', '', 'KOREA', ''),
    ('KIM DEOK SOO', '', 'KOREA', ''),
    ('KANG SEUNG WOO', '', 'KOREA', ''),
    ('SUN JIAN', '', 'CHINA', ''),
    ('JI YICHENG', '', 'CHINA', ''),
    ('SONG JIN SEOK', '', 'KOREA', ''),
    ('BONG JAE YEON', '', 'KOREA', ''),
    ('KIM YOUNG JUN', '', 'KOREA', ''),
    ('PARK SEON GIK', '', 'KOREA', ''),
    ('PARK JI SU', '', 'KOREA', ''),
    ('KANG JOO SEONG', '', 'KOREA', ''),
    ('KANG JIN WOO', '', 'KOREA', ''),
    ('KANG BUM SOO', '', 'KOREA', ''),
    ('JUN SANG WOO', '', 'KOREA', ''),
    ('LIU QINGYUN', '', 'CHINA', ''),
    ('YOON WOOK', '', 'KOREA', ''),
    ('ZHANG LIANG', '', 'CHINA', 'CHINA'),
    ('TSOI ANDREI', '', 'KOREA', ''),
    ('KAN TOR MIKHAEL', '', 'KOREA', ''),
    ('KIM SEUNG YUL', '', 'KOREA', ''),
    ('YU JIN WOO', '', 'KOREA', ''),
    ('ZHU JUNJIE', '', 'KOREA', ''),
    ('BAT ERDENE', '', 'MONGOL', ''),
    ('KANG JIN HO', '', 'KOREA', ''),
    ('KIM JI YOUNG', '', 'KOREA', ''),
    ('KIM SEON HAK', '', 'KOREA', ''),
    ('KIM SUNG HYEON', '', 'KOREA', ''),
    ('PARK SEONG SOO', '', 'KOREA', ''),
    ('MAI VAN DAO', '', 'VIETNAM', ''),
    ('SONG HA JIN', '', 'KOREA', ''),
    ('BEAK JONG HUN', '', 'KOREA', ''),
    ('KIM YEONG CHEOL', '', 'KOREA', ''),
    ('JIN BYUNG WAN', '', 'KOREA', ''),
    ('KU DOGYEONG', '', 'KOREA', ''),
    ('KANG MINGI', '', 'KOREA', ''),
    ('GWON SANG YONG', '', 'KOREA', ''),
    ('PARK SUNG WOON', '', 'KOREA', ''),
    ('JUN YOUNG JUN', '', 'KOREA', ''),
    ('RYU JAE JOON', '', 'KOREA', ''),
    ('KIM HYUNJUN', '', 'KOREA', ''),
    ('WANG ZHENSHI', '', 'CHINA', ''),
    ('TSYMBAL DMITRII', '', 'RUSSIA', ''),
    ('JANG KYENG DAL', '', 'KOREA', ''),
    ('PARK SUNG WOON', '', 'KOREA', ''),
    ('KWON OH YOUNG', '', 'KOREA', ''),
    ('VINCENT', '', 'FRANCE', ''),
    ('ALEXANDER', '', 'UK', ''),
    ('MOU JUN', '', 'CHINA', ''),
    ('LEE SU IL', '', 'KOREA', ''),
    ('PARK YOON HYUCK', '', 'KOREA', ''),
    ('AN CHAN YOUNG', '', 'KOREA', ''),
    ('NAM JUNG HYUN', '', 'KOREA', ''),
    ('CHIO JUNSEOK', '', 'KOREA', ''),
    ('BACK CHANG HACK', '', 'KOREA', ''),
    ('KIM SU HA', '', 'KOREA', ''),
    ('KANG TAE YOUNG', '', 'KOREA', ''),
    ('YUN DEUK GWANG', '', 'KOREA', ''),
    ('PARK KI YOUL', '', 'KOREA', ''),
    ('PARK YOUNG GYU', '', 'KOREA', ''),
    ('HUNG YU SHENG', '', 'CHINA', ''),
    ('PARK JUN YOUNG', '', 'KOREA', ''),
    ('TAE JIN KI', '', 'KOREA', ''),
    ('PARK JI HOON', '', 'KOREA', ''),
    ('JEON SEONG KEE', '', 'KOREA', ''),
    ('BONG JAE YEON', '', 'KOREA', ''),
    ('MANDARKBAYAR', '', 'MONGOL', ''),
    ('OCHGEREL GERELSUKH', '', 'MONGOL', ''),
    ('ZENG CEN', '', 'CHINA', ''),
    ('SEO SUNG MIN', '', 'KOREA', ''),
    ('BURTETSETSEN', '', 'MONGOL', ''),
    ('SONG JIN KYU', '', 'KOREA', ''),
    ('JUNG MIN SEO', '', 'KOREA', ''),
    ('GIL SU BIN', '', 'KOREA', ''),
    ('KIM TAE HO', '', 'KOREA', ''),
    ('SONG JUN KYU', '', 'KOREA', ''),
    ('LIM CHAE HOON', '', 'KOREA', ''),
    ('HONG SEUNG PYO', '', 'KOREA', ''),
    ('KIM KYUNG MIN', '', 'KOREA', ''),
    ('PARK SONG WOONG', '', 'KOREA', ''),
    ('LEE SEONG YEOP', '', 'KOREA', ''),
    ('PARK HEON IL', '', 'KOREA', ''),
    ('KAL DEOK KI', '', 'KOREA', ''),
    ('LEE YE CHAN', '', 'KOREA', ''),
    ('PARK MIN CHUN', '', 'KOREA', ''),
    ('KIM CHANG MIN', '', 'KOREA', ''),
    ('YANG JUN HYEOK', '', 'KOREA', ''),
    ('HONG SEOK JUN', '', 'KOREA', ''),
    ('KIM BEOM JUN', '', 'KOREA', ''),
    ('KIM JEE WEON', '', 'HOUSE', ''),
    ('KIM MIN JUN', '', 'KOREA', ''),
    ('CHA SOON JOO', '', 'KOREA', ''),
    ('KIM YONG SUNG', '', 'KOREA', ''),
    ('YU YOUNG GON', '', 'KOREA', ''),
    ('YOU CHANG KYUN', '', 'KOREA', ''),
    ('AM INO', '', 'KOREA', ''),
    ('KWON SEOU', '', 'KOREA', ''),
    ('KIM DAE HUYN', '', 'KOREA', ''),
    ('JANG WOO SUNG', '', 'KOREA', ''),
    ('SUN JIN', '', 'KOREA', ''),
    ('KIM JIMIN', '', 'KOREA', ''),
    ('LEE KWANG TAE', '', 'KOREA', ''),
    ('LEE CHAN GIN', '', 'KOREA', ''),
    ('JEONG HYUN DO', '', 'KOREA', ''),
    ('KWON HYE SUNG', '', 'KOREA', ''),
    ('KIM SHIN HEE', '', 'KOREA', ''),
    ('KIM KYEONG WOOK', '', 'KOREA', ''),
    ('CHUNG UI HOON', '', 'KOREA', ''),
    ('YOO DONG JU', '', 'KOREA', ''),
    ('JEONG HUI JIN', '', 'KOREA', ''),
    ('HAEUN PARK', '', 'KOREA', ''),
    ('LEE HOCHEOL', '', 'KOREA', ''),
    ('LEE DAE YANG', '', 'KOREA', ''),
    ('EOM YONGHOON', '', 'KOREA', ''),
    ('KIM HUYNMIN', '', 'KOREA', ''),
    ('CHA PHILLIP', '', 'KOREA', ''),
    ('JEONG SEONGUN', '', 'KOREA', ''),
    ('CHOI KONG HUN', '', 'KOREA', ''),
    ('YANG JUNMO', '', 'KOREA', ''),
    ('KIM KAPJUNG', '', 'KOREA', ''),
    ('LEE SEUNGHWAN', '', 'KOREA', ''),
    ('JO SEONU', '', 'KOREA', ''),
    ('KIM JEONSU', '', 'KOREA', ''),
    ('SONG YOUNG TAK', '', 'KOREA', ''),
    ('LEE SANG UK', '', 'KOREA', ''),
    ('KWON TAE HYEON', '', 'KOREA', ''),
    ('JUNG YOUNG CHUL', '', 'KOREA', ''),
    ('KIM JINHO', '', 'KOREA', ''),
    ('PARK HYUNBEEN', '', 'KOREA', ''),
    ('OH KIHOON', '', 'KOREA', ''),
    ('KIM TAEHO', '', 'KOREA', ''),
    ('JEONG KWANG HEE', '', 'KOREA', ''),
    ('CHAE HEESUNG', '', 'KOREA', ''),
    ('TANG KIM KUEN', '', 'CHINA', 'CHINA'),
    ('WING LOK LEON', '', 'GERMANY', 'GERMANY'),
    ('JUNG JAE WOONG', '', 'KOREA', ''),
    ('KIM JI HUN', '', 'KOREA', ''),
    ('KIM JEHO', '', 'KOREA', ''),
    ('MURAKAMI JUNICHI', '', 'JAPAN', ''),
    ('ITAKURA KENTA', '', 'JAPAN', ''),
    ('KNIGHT HAROLD', '', 'UK', 'UK'),
    ('HWANG SUN WOOK', '', 'KOREA', ''),
    ('JEON SANG HO', '', 'KOREA', ''),
    ('JEONG UI SEON', '', 'KOREA', ''),
    ('HEO MIN SIK', '', 'KOREA', ''),
    ('URASAWA', '', 'JAPAN', ''),
    ('KIM SEONG HO', '', 'KOREA', ''),
    ('PARK JAE HUYN', '', 'KOREA', ''),
    ('LEE HAE WON', '', 'KOREA', ''),
    ('SONG JUNG HO', '', 'KOREA', ''),
    ('SHIN YONG SUK', '', 'KOREA', ''),
    ('JUNG CHAN WU', '', 'KOREA', ''),
    ('YU KANG MIN', '', 'KOREA', ''),
    ('LEE YER YUNG', '', 'KOREA', ''),
    ('KIM HYUNG SUK', '', 'KOREA', ''),
    ('CHOI JUN HAN', '', 'KOREA', ''),
    ('CHOGO KENTO', '', 'JAPAN', ''),
    ('SUZUKI JUMPEI', '', 'JAPAN', ''),
    ('HAN HEE MAN', '', 'KOREA', ''),
    ('LEE WON WOO', '', 'KOREA', ''),
    ('KIM HYEONG JUN', '', 'KOREA', ''),
    ('RYU JEONG MIN', '', 'KOREA', ''),
    ('PARK YEONG WOONG', '', 'KOREA', ''),
    ('LEE YEON DEUG', '', 'KOREA', ''),
    ('NAM WOO HYEUNG', '', 'KOREA', ''),
    ('CORDINGLEY OLIVER JAMES', '', 'UK', ''),
    ('HONG DAE HWA', '', 'KOREA', ''),
    ('TOLSTYKH RIRILL', '', 'RUSSIA', ''),
    ('WANG HAONAN', '', 'CHINA', ''),
    ('KIM HYUNG WOON', '', 'HOUSE', ''),
    ('YANG JUNG BIN', '', 'KOREA', ''),
    ('KIM JI WOO', '', 'KOREA', ''),
    ('KIM DONG HUI', '', 'KOREA', ''),
    ('YAGURA YUKO', '', 'JAPAN', ''),
    ('KANG CHANG WOO', '', 'KOREA', ''),
    ('PARK BYOUNG JOON', '', 'KOREA', ''),
    ('BAE YOUNG HO', '', 'KOREA', ''),
    ('KIM JI YOO', '', 'KOREA', ''),
    ('YOSHIHARA SAKI', '', 'JAPAN', ''),
    ('LEE HYEOK KI', '', 'KOREA', ''),
    ('KURIHARA MARIKA', '', 'JAPAN', ''),
    ('YU SEONG JAE', '', 'KOREA', ''),
    ('ANDREI KULIKOV', '', 'RUSSIA', ''),
    ('ALEKSANDR', '', 'RUSSIA', ''),
    ('LIM JAE BOK', '', 'KOREA', ''),
    ('PHILIP MYUNGHUN', '', 'CANADA', ''),
    ('CHRISTOPHER', '', 'CANADA', ''),
    ('JOO CHEOL HYEON', '', 'KOREA', ''),
    ('LEE BYUNG SOO', '', 'KOREA', ''),
    ('EERO JALMARI', '', 'UK', ''),
    ('MASI JULIUS', '', 'UK', ''),
    ('REED RODERICK ALAN CHUNG', '', 'UK', ''),
    ('CHEN CHUAN', '', 'CHINA', ''),
    ('AHN BYEONG CHAN', '', 'KOREA', ''),
    ('LEE GEUN TAK', '', 'KOREA', ''),
    ('ILIA GUNIN', '', 'RUSSIA', ''),
    ('PARK CHUL WOO', '', 'KOREA', ''),
    ('HYDERABAD NANNAKA', '', 'INDIA', ''),
    ('JUPALLI NIKHIL', '', 'INDIA', ''),
    ('CHAITANYA', '', 'INDIA', ''),
    ('SAHNI CHIRAG', '', 'INDIA', ''),
    ('PUNUKOLLU SUMANTH', '', 'INDIA', ''),
    ('NANNAKA AJAY', '', 'INDIA', ''),
    ('LEE DAE JIN', '', 'HOUSE', ''),
    ('YANG JUN MO', '', 'KOREA', ''),
    ('OH HYUNG KYO', '', 'KOREA', ''),
    ('LIM JAE HUN', '', 'KOREA', ''),
    ('KANG MIN HO', '', 'KOREA', ''),
    ('LEE SANG GUNE', '', 'KOREA', ''),
    ('CHEN CHENGYAO', '', 'CHINA', ''),
    ('KIM HO HWAN', '', 'KOREA', ''),
    ('KIM JAE HEE', '', 'KOREA2', '')
)
insert into public.players(name,card_no,agency_id,note)
select
  s.name,
  nullif(s.card_no,''),
  a.id,
  nullif(s.note,'')
from src s
join public.agencies a on a.code=s.agency_code;

select
  (select count(*) from public.players) as players_imported,
  (select count(*) from public.game_entries) as game_entries_remaining;
